### ISSUE TITLE
PyPDF2.errors.PdfReadError: Invalid Elementary Object starting with b'b' 

### ISSUE THREAD

**Issue by michelcrypt4d4mus** [py-pdf/pypdf#1393]
## Environment
macOS monterey, 12.6
encountered in context of running [the pdfalyzer](https://github.com/michelcrypt4d4mus/pdfalyzer) against various files

```bash
$ python -m platform
macOS-12.6-arm64-arm-64bit

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.11.0
```

## Code + PDF
```python
pdf = open("mac malware book objective see/CH 2 Persistence.pdf", 'rb')
pdf_reader = PdfReader(pdf)
obj = IndirectObject(500, 0, pdf_reader)
obj.get_object()
```

Ran into this error trying to parse all of these PDFs: 
1. https://taomm.org/vol1/pdfs/Part%20I.pdf
1. https://taomm.org/vol1/pdfs/CH%201%20Infection%20Vectors.pdf
1. https://taomm.org/vol1/pdfs/CH%202%20Persistence.pdf
1. ...and all the other chapters found [here](https://taomm.org/vol1/read.html)

with [the pdfalyzer](https://github.com/michelcrypt4d4mus/pdfalyzer):
```bash
pdfalyze -r "mac malware book objective see/CH 2 Persistence.pdf"
```

## Traceback

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/uzer/Library/Caches/pypoetry/virtualenvs/pdfalyzer-EerWfplO-py3.10/lib/python3.10/site-packages/PyPDF2/generic/_base.py", line 164, in get_object
    obj = self.pdf.get_object(self)
  File "/Users/uzer/Library/Caches/pypoetry/virtualenvs/pdfalyzer-EerWfplO-py3.10/lib/python3.10/site-packages/PyPDF2/_reader.py", line 1222, in get_object
    retval = read_object(self.stream, self)  # type: ignore
  File "/Users/uzer/Library/Caches/pypoetry/virtualenvs/pdfalyzer-EerWfplO-py3.10/lib/python3.10/site-packages/PyPDF2/generic/_data_structures.py", line 862, in read_object
    raise PdfReadError(
PyPDF2.errors.PdfReadError: Invalid Elementary Object starting with b'b' @27
```

**Comment by abyesilyurt** [comment]
I can't reproduce the error on main.

**Comment by pubpub-zz** [comment]
@abyesilyurt thanks for your test
@michelcrypt4d4mus can you confirm in your context with the upgrade to the latest realease and if fixed, close the issue

**Comment by pubpub-zz** [comment]
I close this issue as fixed based on @abyesilyurt feed back
