### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by addmein** [py-pdf/pypdf#140]
```
Traceback (most recent call last):
  File "...\merge_pdf_list.py", line 15, in <module> 
     mergePDF()
  File "...\merge_pdf_list.py", line 12, in mergePDF
    writer.write(out)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 315, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 404, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 380, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 404, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
[ line 380 error ]
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 389, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
[ line 404 error ]
[ line 380 error ]  
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 389, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 418, in _sweepIndirectReferences
    newobj = self._sweepIndirectReferences(externMap, newobj)

[...] Lines 404 and 380 errors

  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 409, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "C:\Python27\lib\site-packages\PyPDF2\pdf.py", line 1378, in getObject
    retval = readObject(self.stream, self)
  File "C:\Python27\lib\site-packages\PyPDF2\generic.py", line 63, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "C:\Python27\lib\site-packages\PyPDF2\generic.py", line 569, in readFromStream
    value = readObject(stream, pdf)
  File "C:\Python27\lib\site-packages\PyPDF2\generic.py", line 93, in readObject
    return IndirectObject.readFromStream(stream, pdf)
  File "C:\Python27\lib\site-packages\PyPDF2\generic.py", line 218, in readFromStream
    return IndirectObject(int(idnum), int(generation), pdf)
RuntimeError: maximum recursion depth exceeded
```

**Comment by cryptid11** [comment]
Same here...

**Comment by justinlindh-wf** [comment]
Has anybody found a workaround to this issue? I'm encountering it as well.

**Comment by seanlis** [comment]
This still happens in 1.25.1 with this file:
https://github.com/seanlis/seanlis.github.io/blob/master/tmp/PyPDF2_split_error.pdf.

My code:
```python
inputpdf = PdfFileReader(open("PyPDF2_split_error.pdf", "rb"))

output = PdfFileWriter()
output.addPage(inputpdf.getPage(5))
with open("document-page%s.pdf" % 5, "wb") as outputStream:
    output.write(outputStream)
```

traceback:
```
Traceback (most recent call last):
  File "mytest.py", line 18, in <module>
    output.write(outputStream)
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 467, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 556, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 532, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 556, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 532, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 541, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 556, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 532, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 541, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 570, in _sweepIndirectReferences
...
1955 lines of similar output
...
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 561, in _sweepIndirectReferences
    newobj = data.pdf.getObject(data)
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1564, in getObject
    retval = self._getObjectFromStream(indirectReference)
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 1538, in _getObjectFromStream
    obj = readObject(streamData, self)
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/generic.py", line 66, in readObject
    return DictionaryObject.readFromStream(stream, pdf)
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/generic.py", line 575, in readFromStream
    value = readObject(stream, pdf)
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/generic.py", line 71, in readObject
    return ArrayObject.readFromStream(stream, pdf)
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/generic.py", line 166, in readFromStream
    arr.append(readObject(stream, pdf))
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/generic.py", line 98, in readObject
    return NumberObject.readFromStream(stream)
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/generic.py", line 269, in readFromStream
    return NumberObject(num)
  File "/home/sean/.local/lib/python2.7/site-packages/PyPDF2/generic.py", line 252, in __new__
    val = int(value)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```


But for some pages, it works fine, like 'getPage(0)' or 'getPage(1)'.

**Comment by andya9** [comment]
I can confirm too it still happens on 1.25

**Comment by jeffreycentex** [comment]
Mine is similar when doing a merge, but with fewer pages (about 50-60 pages).  #268 

Mine ends with:

>  File "C:\Anaconda\lib\site-packages\PyPDF2\pdf.py", line 547, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Anaconda\lib\site-packages\PyPDF2\pdf.py", line 571, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Anaconda\lib\site-packages\PyPDF2\pdf.py", line 552, in _sweepIndirectReferences
    data[key] = value
  File "C:\Anaconda\lib\site-packages\PyPDF2\generic.py", line 502, in __setitem__
    if not isinstance(key, PdfObject):
RuntimeError: maximum recursion depth exceeded in __instancecheck__

**Comment by Sayed-Soroush-Hashemi** [comment]
any news? still having it with v 1.26.0 . 

@justinlindh-wf 
did 1500 totally worked for you? or it asked for more in bigger cases?

**Comment by tdg5** [comment]
I'm not a python guy, but this would appear to me to still be an issue with v1.26.0. I was hitting the recursion error via pdfshuffler which I verified was using the 1.26.0 version of this package by adding a print statement to the package installed by pip. The only way I was able to find success was by increasing the recursion limit as suggested by @justinlindh-wf.

**Comment by CoolestNerdIII** [comment]
I am also still having this issue with 1.26.0

In may case, I am using the Merger, and have managed to work around this issue by splitting the merging process into multiple steps. It was occurring for me when I was essentially merging around 5000+ files, so I split that into merging 100 at a time (using multiprocessing) and then merging the results. It seems to be a bit of a convoluted solution, but works for me right now. If there are any updates on this, it would be greatly appreciated :)

**Comment by zMingGit** [comment]
same problem.

**Comment by pelzhaus** [comment]
Getting the same recursion even when writing a single page. Any other known workarounds?

**Comment by wrnrlr** [comment]
I'm getting the same problem with this pdf: 
http://www.ejustice.just.fgov.be/mopdf/2018/08/14_1.pdf

**Comment by adigandhi** [comment]
Same error on a part datasheet, 907 pages.

**Comment by Hendiadyoin1** [comment]
same/similar error when merging more than a hundred files at once

**Comment by glanderson42** [comment]
You just need to set the recursion limit in python itself. 
`
import sys
sys.setrecursionlimit(150000) # set it to enugh big
`

**Comment by mjoaovictor** [comment]
I set the Recursion Limit on Python to 2000. It's not a fix yet, but a workaround that works.

```
import sys
sys.setrecursionlimit(2000)
```

**Comment by santiagofacchini** [comment]
Still having the same recursion issue here, using PyPDF2 1.26.0, workaround:

```
import sys
sys.setrecursionlimit(2000)
```

**Comment by MartinThoma** [comment]
@santiagofacchini Why are you still using `PyPDF2==1.26.0` and not `PyPDF2==1.27.8`?

**Comment by santiagofacchini** [comment]
@MartinThoma This is the code, just a simple pdf merger:

```
import os
import PyPDF2


pdf_files = os.listdir('/dir')
merged_object = PyPDF2.PdfFileMerger()

for pdf_file in sorted(pdf_files):
    if pdf_file.endswith('.pdf'):
        merged_object.append(PyPDF2.PdfFileReader(f'/dir/{pdf_file}', 'rb'))

merged_object.write(f'/dir/merged.pdf')
```

I just updated to `1.27.8`, thanks!

**Comment by MartinThoma** [comment]
This works just fine with the files in `Resources` (btw: You want `PyPDF2.PdfFileReader(pathon)` - without the `'rb'` parameter).

**Comment by MartinThoma** [comment]
If you can't reproduce this any longer, I will assume for the moment that this is fixed with the recent updates. If people run into it again, they can file another issue / I can re-open this one.

**Comment by Triptolemus** [comment]
This should be re-opened. I'm experiencing this issue currently. Using 1.27.9, Python 3.10. Merging 14 PDFs containing 80 or so pages.

**Comment by MartinThoma** [comment]
@Triptolemus I've merged hundreds of PDF in one 8000+ page PDF without issues. Could you please check for PyPDF2==2.3.1 if the issue still exists??

**Comment by MartinThoma** [comment]
I guess this problem was solved with recent PyPDF2 versions. Please let me know if you still encounter this issue.

**Comment by pubpub-zz** [comment]
When I open your pdf with acrobat reader page 13/14 can not be displayed : It looks too damaged to be opened with pypdf. I have no solution to propose you.

**Comment by MartinThoma** [comment]
I want to have a look at it. Infinite loops should never happen, even if the file being opened is not a PDF at all or damaged beyond repair. An infinite loop might block a process.

**Comment by xilopaint** [comment]
> @MartinThoma I'm still getting this error, with this file:
> [bad_pdf_example.pdf](https://github.com/py-pdf/pypdf/files/12168578/bad_pdf_example.pdf)

@MartinThoma is this file beyond repair?

**Comment by MartinThoma** [comment]
@xilopaint What do you mean? The latest pypdf version can extract text from it. So obviously now.

**Comment by xilopaint** [comment]
> @xilopaint What do you mean? The latest pypdf version can extract text from it. So obviously now.

@MartinThoma In v3.15.2 I got a TypeError while attempting to merge this file. It no longer enters an infinite loop, though.

**Comment by MartinThoma** [comment]
Huh, interesting. In 3.15.4 I don't get a TypeError. Can you please test again with the latest version?

**Comment by xilopaint** [comment]
@MartinThoma Same error. Here the log:

```log
08:28:10 _utils.py:452 WARNING  incorrect startxref pointer(2)
08:28:11 _utils.py:452 WARNING  Object 627 0 not defined.
08:28:11 _utils.py:452 WARNING  Object 674 0 not defined.
08:28:11 _utils.py:452 WARNING  Object 737 0 not defined.
08:28:11 _utils.py:452 WARNING  Object 609 0 not defined.
08:28:11 _utils.py:452 WARNING  Object 611 0 not defined.
08:28:11 _utils.py:452 WARNING  Object 613 0 not defined.
08:28:11 _utils.py:452 WARNING  Object 616 0 not defined.
08:28:11 workflow.py:2352 ERROR    '>' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/workflow/workflow.py", line 2346, in run
    func(self)
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/alfred_pdf_tools.py", line 573, in main
    merge(query, pdf_paths)
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/alfred_pdf_tools.py", line 76, in wrapper
    func(*args, **kwargs)
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/alfred_pdf_tools.py", line 288, in merge
    writer.append(reader)
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/_writer.py", line 2854, in append
    self.merge(
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/_utils.py", line 468, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/_writer.py", line 2935, in merge
    srcpages[pg.indirect_reference.idnum] = self.add_page(
                                            ^^^^^^^^^^^^^^
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/_writer.py", line 391, in add_page
    return self._add_page(page, list.append, excluded_keys)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/_writer.py", line 324, in _add_page
    page = cast("PageObject", page_org.clone(self, False, excluded_keys))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/generic/_data_structures.py", line 197, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/generic/_data_structures.py", line 297, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/generic/_base.py", line 295, in clone
    obj.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/generic/_data_structures.py", line 197, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/generic/_data_structures.py", line 297, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/generic/_data_structures.py", line 197, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/generic/_data_structures.py", line 297, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/generic/_base.py", line 295, in clone
    obj.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/generic/_data_structures.py", line 197, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/generic/_data_structures.py", line 819, in _clone
    super()._clone(src, pdf_dest, force_duplicate, ignore_fields)
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/generic/_data_structures.py", line 297, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/generic/_base.py", line 287, in clone
    obj = self.get_object()
          ^^^^^^^^^^^^^^^^^
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/generic/_base.py", line 307, in get_object
    obj = self.pdf.get_object(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/_reader.py", line 1387, in get_object
    retval = read_object(self.stream, self)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/generic/_data_structures.py", line 1253, in read_object
    return DictionaryObject.read_from_stream(stream, pdf, forced_encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Developer/GitHub/Personal Projects/Alfred Workflows/Alfred PDF Tools/alfred-pdf-tools/src/pypdf/generic/_data_structures.py", line 500, in read_from_stream
    if length > 0:
       ^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by MartinThoma** [comment]
@xilopaint Can you please execute `python -c "import pypdf;print(pypdf._debug_versions)"` and share the result?

**Comment by xilopaint** [comment]
@MartinThoma 

```
$ python3 -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.15.4, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=none
```

**Comment by MartinThoma** [comment]
I cannot reproduce.

@xilopaint please sahre a minimal code example.

**Comment by xilopaint** [comment]
@MartinThoma 

```python3
from pypdf import PdfReader, PdfWriter

pdfs = ["bad_pdf_example.pdf", "bad_pdf_example_copy.pdf"]

writer = PdfWriter()

for pdf in pdfs:
    reader = PdfReader(pdf)
    writer.append(reader)

writer.write("merged.pdf")
print("Merge completed successfully.")
```

**Comment by pubpub-zz** [comment]
the PDF is damaged.The length is an indirectobject that can not be found returning None. The PR is fixing it

**Comment by JuanQP** [comment]
I had a file with 1200 pages and I was having this `maximum recursion depth exceeded` error. The error was specifically thrown when I tried to access the `.pages` property:

```python
for page in pdf_file.pages: # -> maximum recursion depth exceeded
    # Code...
```

But for some reason, if I tried  to access its pages again, it will work:


```python
try:
    len(pdf_file.pages) # -> first try: maximum recursion depth exceeded
except:
    pass

for page in pdf_file.pages: # Second try, now it works!
    # Code...
```

It seems that pages are somehow related with the Python maximum depth configuration. So, it seems that it will fail on the first attempt, but then, on the second attempt will continue with the previous results and finally succeed

I know it's a little bit messy, but it's a workaround that worked for me. Hope this helps someone

**Comment by AnotherYx** [comment]
I encountered this error while using PyPDF2==3.0.2 to process https://downloads.mysql.com/docs/refman-9.0-en.a4.pdf:

reader = PdfReader("example-docs/mysql-refman-9.0-en.a4.pdf")
total_pages = len(reader.pages)
print(f"PDF total pages: {total_pages}") #6022
writer = PdfWriter()
start_page = 1837 
end_page = 1897    
for page_num in range(start_page, end_page):
    writer.add_page(reader.pages[page_num])

with open("example-docs/mysqlLanguageStructure.pdf", "wb") as output_pdf:
    writer.write(output_pdf)
Traceback (most recent call last):
  File "/home/111/anaconda3/lib/python3.11/site-packages/PyPDF2/generic/_data_structures.py", line 386, in read_from_stream
    value = read_object(stream, pdf, forced_encoding)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/111/anaconda3/lib/python3.11/site-packages/PyPDF2/generic/_data_structures.py", line 1049, in read_object
    return ArrayObject.read_from_stream(stream, pdf, forced_encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/111/anaconda3/lib/python3.11/site-packages/PyPDF2/generic/_data_structures.py", line 150, in read_from_stream
    arr.append(read_object(stream, pdf, forced_encoding))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/111/anaconda3/lib/python3.11/site-packages/PyPDF2/generic/_data_structures.py", line 1077, in read_object
    return NumberObject.read_from_stream(stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/111/anaconda3/lib/python3.11/site-packages/PyPDF2/generic/_base.py", line 405, in read_from_stream
    num = read_until_regex(stream, NumberObject.NumberPattern)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:
......
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by stefan6419846** [comment]
PyPDF2 is EOL. Please switch to the latest *pypdf* version. If the issue persists, please open a proper bug report for further analysis.

**Comment by AnotherYx** [comment]
> I encountered this error while using PyPDF2==3.0.2 to process https://downloads.mysql.com/docs/refman-9.0-en.a4.pdf:
> 
> reader = PdfReader("example-docs/mysql-refman-9.0-en.a4.pdf") total_pages = len(reader.pages) print(f"PDF total pages: {total_pages}") #6022 writer = PdfWriter() start_page = 1837 end_page = 1897 for page_num in range(start_page, end_page): writer.add_page(reader.pages[page_num])
> 
> with open("example-docs/mysqlLanguageStructure.pdf", "wb") as output_pdf: writer.write(output_pdf) Traceback (most recent call last): File "/home/111/anaconda3/lib/python3.11/site-packages/PyPDF2/generic/_data_structures.py", line 386, in read_from_stream value = read_object(stream, pdf, forced_encoding) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/111/anaconda3/lib/python3.11/site-packages/PyPDF2/generic/_data_structures.py", line 1049, in read_object return ArrayObject.read_from_stream(stream, pdf, forced_encoding) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/111/anaconda3/lib/python3.11/site-packages/PyPDF2/generic/_data_structures.py", line 150, in read_from_stream arr.append(read_object(stream, pdf, forced_encoding)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/111/anaconda3/lib/python3.11/site-packages/PyPDF2/generic/_data_structures.py", line 1077, in read_object return NumberObject.read_from_stream(stream) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/111/anaconda3/lib/python3.11/site-packages/PyPDF2/generic/_base.py", line 405, in read_from_stream num = read_until_regex(stream, NumberObject.NumberPattern) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ RecursionError: maximum recursion depth exceeded
> 
> During handling of the above exception, another exception occurred: ...... RecursionError: maximum recursion depth exceeded while calling a Python object

However, using this setting can solve the error: sys.setrecursionlimit(15000)

**Comment by pubpub-zz** [comment]
@AnotherYx 
PyPDF2 is no more supported. Move to pypdf, latest release. If problem still occurs open a new issue
