### ISSUE TITLE
PdfReadError:  trailer can not be read ()

### ISSUE THREAD

**Issue by ma-pony** [py-pdf/pypdf#1559]
When I read certain PDF files(maybe not standard pdf), an exception is thrown, 
I hope I can read them normally

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-10.16-x86_64-i386-64bit

$ python -c "import pypdf;print(pypdf.__version__)"
3.2.1
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from io import BytesIO

import requests
from pypdf import PdfReader

if __name__ == '__main__':
    url = "https://gz-gov-open-doc.oss-cn-gz-ysgzlt-d01-a.ltops.gzdata.com.cn/1024FPA/open/37560735-0101-4199-8dd6-c9015c438f13.pdf"
    res = requests.get(url)
    print(res.text)
    PdfReader(BytesIO(res.content))
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!
[小型企业声明函.pdf](https://github.com/py-pdf/pypdf/files/10441992/default.pdf)

## Traceback

This is the complete Traceback I see:
```
Traceback (most recent call last):
  File "/Users/rccpony/Library/Caches/pypoetry/virtualenvs/KPnmHDqb-py3.8/lib/python3.8/site-packages/pypdf/_reader.py", line 1713, in _read_xref_tables_and_trailers
    xrefstream = self._read_pdf15_xref_stream(stream)
  File "/Users/rccpony/Library/Caches/pypoetry/virtualenvs/KPnmHDqb-py3.8/lib/python3.8/site-packages/pypdf/_reader.py", line 1842, in _read_pdf15_xref_stream
    self._read_xref_subsections(idx_pairs, get_entry, used_before)
  File "/Users/rccpony/Library/Caches/pypoetry/virtualenvs/KPnmHDqb-py3.8/lib/python3.8/site-packages/pypdf/_reader.py", line 1907, in _read_xref_subsections
    assert start >= last_end
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rccpony/PycharmProjects/pdf.py", line 10, in <module>
    PdfReader(BytesIO(res.content))
  File "/Users/rccpony/Library/Caches/pypoetry/virtualenvs/KPnmHDqb-py3.8/lib/python3.8/site-packages/pypdf/_reader.py", line 319, in __init__
    self.read(stream)
  File "/Users/rccpony/Library/Caches/pypoetry/virtualenvs/KPnmHDqb-py3.8/lib/python3.8/site-packages/pypdf/_reader.py", line 1508, in read
    self._read_xref_tables_and_trailers(stream, startxref, xref_issue_nr)
  File "/Users/rccpony/Library/Caches/pypoetry/virtualenvs/KPnmHDqb-py3.8/lib/python3.8/site-packages/pypdf/_reader.py", line 1722, in _read_xref_tables_and_trailers
    raise PdfReadError(f"trailer can not be read {e.args}")
pypdf.errors.PdfReadError: trailer can not be read ()

```

**Comment by pubpub-zz** [comment]
@ma-pony
this looks like a error in the interpretation of the standard. The PR should solve this

**Comment by wasa-ism** [comment]
I am facing the exact issue with this PDF.
[ca-dmv-form-dl-44.pdf](https://github.com/py-pdf/pypdf/files/11456540/ca-dmv-form-dl-44.pdf)

**Comment by pubpub-zz** [comment]
@wasa-ism 
please provide more details : version + test code + error output

**Comment by verhovensky** [comment]
Same here
```
>>> f = PyPDF2.PdfReader('ps1583ssss.pdf')
Previous trailer can not be read ()
>>> f.get_fields()
Object 731 0 found
Object 2325 0 not defined.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bulat/PycharmProjects/api-LLC/.venv/lib/python3.12/site-packages/PyPDF2/_reader.py", line 558, in get_fields
    self._build_field(field, retval, fileobj, field_attributes)
  File "/home/bulat/PycharmProjects/api-LLC/.venv/lib/python3.12/site-packages/PyPDF2/_reader.py", line 583, in _build_field
    self._check_kids(field, retval, fileobj)
  File "/home/bulat/PycharmProjects/api-LLC/.venv/lib/python3.12/site-packages/PyPDF2/_reader.py", line 600, in _check_kids
    if PA.KIDS in tree:
       ^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

```

Python 3.12.0 (main, Jan  2 2025, 15:28:16) [GCC 12.2.0] on linux
PyPDF2==3.0.1
