### ISSUE TITLE
PdfWriter: 'NullObject' object has no attribute 'get'

### ISSUE THREAD

**Issue by chyla** [py-pdf/pypdf#1585]
Merge PDFs eith PdfWriter as per example from https://pypdf.readthedocs.io/en/latest/user/merging-pdfs.html

```python
from pypdf import PdfWriter

merger = PdfWriter()

for pdf in ["file1.pdf", "file2.pdf", "file3.pdf"]:
    merger.append(pdf)

merger.write("merged-pdf.pdf")
merger.close()
```

Old PdfMerger works fine: https://pypdf2.readthedocs.io/en/2.12.0/user/merging-pdfs.html

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.15.0-58-generic-x86_64-with-glibc2.35

$ python -c "import pypdf;print(pypdf.__version__)"
3.3.0

$ pip freeze
pypdf==3.3.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
#!/usr/bin/env python3

from pypdf import PdfWriter

merger = PdfWriter()

merger.append("Operacje-wejscia-wyjscia-Pliki.pdf")

merger.write("output.pdf")
merger.close()
```

Input PDF file: https://chyla.org/_static/files/artykuly/python/python-tutorial/Operacje-wejscia-wyjscia-Pliki.pdf

## Traceback
```
Traceback (most recent call last):
  File "/tmp/m.py", line 7, in <module>
    merger.append("Operacje-wejscia-wyjscia-Pliki.pdf")
  File "/tmp/venv/lib/python3.10/site-packages/pypdf/_writer.py", line 2445, in append
    self.merge(
  File "/tmp/venv/lib/python3.10/site-packages/pypdf/_utils.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "/tmp/venv/lib/python3.10/site-packages/pypdf/_writer.py", line 2554, in merge
    outline = self._get_filtered_outline(
  File "/tmp/venv/lib/python3.10/site-packages/pypdf/_writer.py", line 2757, in _get_filtered_outline
    if node.get("/Type", "") == "/Outlines" or "/Title" not in node:
AttributeError: 'NullObject' object has no attribute 'get'
```

## Working Code

This is a minimal, complete example that is working fine:

```python
#!/usr/bin/env python3

from pypdf import PdfMerger

merger = PdfMerger()

merger.append("Operacje-wejscia-wyjscia-Pliki.pdf")

merger.write("output.pdf")
merger.close()
```

**Comment by pubpub-zz** [comment]
this should be fixed in b785e087a43c884151404c535767b6e7b52e3bd0
this commit is part of #1553 which will be merged very soon
