### ISSUE TITLE
Crashes with multiple files

### ISSUE THREAD

**Issue by atombrella** [py-pdf/pypdf#160]
I have this small piece of code. It works fine with less than ~ 350 pdf files (all generated using the same code!), but with more than that, it crashes with 

```python
def collect_in_pdf_file(pdf_invoices, report):
    merger = PdfFileMerger()
    for filename in pdf_invoices:
        merger.append(PdfFileReader(file(filename, 'rb'), strict=False))
    merger.write(os.path.join('/tmp', 'invoices_{}.pdf'.format(report.pk)))
    return os.path.join('/tmp', 'invoices_{}.pdf'.format(report.pk))
```
gives

```
Traceback (most recent call last):
  File "/var/www/cms/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "/var/www/cms/local/lib/python2.7/site-packages/celery/app/trace.py", line 437, in **protected_call**
    return self.run(_args, *_kwargs)
  File "/var/www/cms/current/storefront/lib/warehouse/workers/orders.py", line 206, in norway_generate_repo$
    norway_customs_report()
  File "/var/www/cms/current/storefront/lib/warehouse/handlers/customs_report.py", line 314, in norway_cust$
    invoice_pdf = collect_in_pdf_file(pdf_invoices, report)
  File "/var/www/cms/current/storefront/lib/warehouse/handlers/customs_report.py", line 133, in collect_in_$
    merger.write(os.path.join('/tmp', 'invoices_{}.pdf'.format(report.pk)))
  File "/var/www/cms/local/lib/python2.7/site-packages/PyPDF2/merger.py", line 227, in write
    self.output.write(fileobj)
  File "/var/www/cms/local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 315, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "/var/www/cms/local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 404, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/var/www/cms/local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 380, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "/var/www/cms/local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 404, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "/var/www/cms/local/lib/python2.7/site-packages/PyPDF2/pdf.py", line 380, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
stack trace continues with the same repeated pattern as the last two lines.
```

I use PyPDF 1.23, reportlab  $Id: **init**.py 3649 2010-01-20 14:45:53Z damian $ (because of xhtml2pdf. I can merge the files effortlessly with ghostscript, and none of the pdf files are corrupted! I tried to add strict=False to remedy the issue (I've had the problem a few times).

**Comment by MartinThoma** [comment]
Uh, interesting! I wonder if it's about the number of pdf pages or about the documents... Or something completely different.

Things might also have changed since 2014

**Comment by MartinThoma** [comment]
Updating the script to PyPDF2 2 syntax:

```python
from PyPDF2 import PdfMerger

def collect_in_pdf_file(pdf_invoices, report):
    merger = PdfMerger()
    for filename in pdf_invoices:
        merger.append(PdfMerger(filename, strict=False))
    merger.write(os.path.join('/tmp', 'invoices_{}.pdf'.format(report.pk)))
    return os.path.join('/tmp', 'invoices_{}.pdf'.format(report.pk))
```

**Comment by MartinThoma** [comment]
> Not sure how you can test and close a ticket in the same moment without testing edge cases too

If you can show me those edge cases, I can reopen the issue. Until then, I assume the problem is solved. 

> this project is dead now

That is not the case! I am the new maintainer. PyPDF2 is masking great progress as excellent developers contributed a lot in the past weeks.
