### ISSUE TITLE
"IndexError: list index out of range" while merging a specific PDF document

### ISSUE THREAD

**Issue by barsch** [py-pdf/pypdf#1652]
Merging a specific non encrypted PDF document throws an "IndexError: list index out of range" - this works flawless for other documents but this one document I can not merge. A similar error occurs while reading this document (without error) and than writing again. Providing ```strict=True``` does not result into any additional output.

## Environment

Which environment were you using when you encountered the problem?

```cmd
C:\>python -V
Python 3.8.10

C:\>python -m platform
Windows-10-10.0.19045-SP0

C:\>python -c "import pypdf;print(pypdf.__version__)"
3.4.1
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfMerger

merger = PdfMerger()
merger.append(path_to_file)
```

I can't share the PDF publicly as it contains personal data (invoices). Let me know where to send it via email.

## Traceback
```
Traceback (most recent call last):
  File "D:\Workspace\egu\src\egu\blah.py", line 4, in <module>
    merger.append(
  File "D:\Python\virtualenv\egu\lib\site-packages\pypdf\_utils.py", line 441, in wrapper
    return func(*args, **kwargs)
  File "D:\Python\virtualenv\egu\lib\site-packages\pypdf\_merger.py", line 317, in append
    self.merge(len(self.pages), fileobj, outline_item, pages, import_outline)
  File "D:\Python\virtualenv\egu\lib\site-packages\pypdf\_utils.py", line 441, in wrapper
    return func(*args, **kwargs)
  File "D:\Python\virtualenv\egu\lib\site-packages\pypdf\_merger.py", line 217, in merge
    outline = reader.outline
  File "D:\Python\virtualenv\egu\lib\site-packages\pypdf\_reader.py", line 799, in outline
    return self._get_outline()
  File "D:\Python\virtualenv\egu\lib\site-packages\pypdf\_reader.py", line 828, in _get_outline
    self._namedDests = self._get_named_destinations()
  File "D:\Python\virtualenv\egu\lib\site-packages\pypdf\_reader.py", line 756, in _get_named_destinations
    self._get_named_destinations(kid.get_object(), retval)
  File "D:\Python\virtualenv\egu\lib\site-packages\pypdf\_reader.py", line 762, in _get_named_destinations
    value = names[i + 1].get_object()
IndexError: list index out of range
```

**Comment by pubpub-zz** [comment]
Do you agree to share the document through @MartinThoma (info@martin-thoma.de)?

**Comment by pubpub-zz** [comment]
By the way can you rerun it using PdfWriter instead of PdfMerger. This class is now deprecated.

**Comment by barsch** [comment]
> Do you agree to share the document through @MartinThoma ([info@martin-thoma.de](mailto:info@martin-thoma.de))?

email has been sent - thanks in advance

**Comment by pubpub-zz** [comment]
> By the way can you rerun it using PdfWriter instead of PdfMerger. This class is now deprecated.

Any results?

**Comment by barsch** [comment]
> > By the way can you rerun it using PdfWriter instead of PdfMerger. This class is now deprecated.
> 
> Any results?

```
from pypdf import PdfWriter

merger = PdfWriter()
merger.append("D:\\Downloads\\attachment_0db1912fe8e137a2aad17d5b3b754e2eb.pdf")
```

results into

```
Traceback (most recent call last):
  File "D:\Workspace\egu\src\blah.py", line 4, in <module>
    merger.append("D:\\Downloads\\attachment_0db1912fe8e137a2aad17d5b3b754e2eb.pdf")
  File "D:\Python\virtualenv\egu\lib\site-packages\pypdf\_writer.py", line 2476, in append
    self.merge(
  File "D:\Python\virtualenv\egu\lib\site-packages\pypdf\_utils.py", line 441, in wrapper
    return func(*args, **kwargs)
  File "D:\Python\virtualenv\egu\lib\site-packages\pypdf\_writer.py", line 2563, in merge
    reader.named_destinations
  File "D:\Python\virtualenv\egu\lib\site-packages\pypdf\_reader.py", line 515, in named_destinations
    return self._get_named_destinations()
  File "D:\Python\virtualenv\egu\lib\site-packages\pypdf\_reader.py", line 756, in _get_named_destinations
    self._get_named_destinations(kid.get_object(), retval)
  File "D:\Python\virtualenv\egu\lib\site-packages\pypdf\_reader.py", line 762, in _get_named_destinations
    value = names[i + 1].get_object()
IndexError: list index out of range
```

**Comment by pubpub-zz** [comment]
@barsch 
the file is not respecting the Pdf Standard : one name is double(acceptable) but no destination is provided. Acrobat Reader tolerates this error, therefore I'm ok to propose a PR:
meanwhile if you want to patch your machine, find the new code for _get_named_destination()  in _reader.py:
```
    def _get_named_destinations(
        self,
        tree: Union[TreeObject, None] = None,
        retval: Optional[Any] = None,
    ) -> Dict[str, Any]:
        """
        Retrieve the named destinations present in the document.

        Args:
            tree:
            retval:

        Returns:
            A dictionary which maps names to
            :class:`Destinations<pypdf.generic.Destination>`.
        """
        if retval is None:
            retval = {}
            catalog = cast(DictionaryObject, self.trailer[TK.ROOT])

            # get the name tree
            if CA.DESTS in catalog:
                tree = cast(TreeObject, catalog[CA.DESTS])
            elif CA.NAMES in catalog:
                names = cast(DictionaryObject, catalog[CA.NAMES])
                if CA.DESTS in names:
                    tree = cast(TreeObject, names[CA.DESTS])

        if tree is None:
            return retval

        if PA.KIDS in tree:
            # recurse down the tree
            for kid in cast(ArrayObject, tree[PA.KIDS]):
                self._get_named_destinations(kid.get_object(), retval)
        # TABLE 3.33 Entries in a name tree node dictionary (PDF 1.7 specs)
        elif CA.NAMES in tree:  # KIDS and NAMES are exclusives (PDF 1.7 specs p 162)
            names = cast(DictionaryObject, tree[CA.NAMES])
            for i in range(0, len(names), 2):
                key = cast(str, names[i].get_object())
                if not isinstance(key,str):
                    continue
                try:
                    value = names[i + 1].get_object()
                except IndexError:
                    break
                if isinstance(value, DictionaryObject) and "/D" in value:
                    value = value["/D"]
                dest = self._build_destination(key, value)  # type: ignore
                if dest is not None:
                    retval[key] = dest
        else:  # case where Dests is in root catalog (PDF 1.7 specs, §2 about PDF1.1
            for k__, v__ in tree.items():
                val = v__.get_object()
                dest = self._build_destination(k__, val)
                if dest is not None:
                    retval[k__] = dest
        return retval
```

**Comment by pubpub-zz** [comment]
The ticket will be closed automatically when the  PR will be merged
