### ISSUE TITLE
KeyError: 'forward reference to "FormXob.{\'/CropBox\': RectangleObject

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [py-pdf/pypdf#1688]
My goal:

An A4 PDF file has two columns. Read it with Python and output a new A5 PDF file where the width of the column corresponds to the width of the A5 page (enlarge/reduce if necessary) and copy the complete content into a new A5 PDF. If you do it right, there will be more pages in the A5 PDF file than in the A4 PDF file. Also take over chapters.

My code:

    import PyPDF2
    from reportlab.pdfgen import canvas
    from reportlab.lib.units import mm
    with open(r'c.pdf', 'rb') as a4_file:
        a4_reader = PyPDF2.PdfReader(a4_file)
        num_pages = len(a4_reader.pages)
        a5_width = 148 * mm
        a5_height = 210 * mm
        a5_canvas = canvas.Canvas(r'v.pdf', pagesize=(a5_width, a5_height))
        bookmarks = []
        for i in range(num_pages):
            a4_page = a4_reader.pages[i]
            a4_width = a4_page.mediabox.width
            a4_height = a4_page.mediabox.height
            column_width = a4_width / 2
            width_scale = a5_width / float(column_width)
            height_scale = a5_height / a4_height
            scale = min(width_scale, height_scale)
            a4_page.scale(scale, scale)
            
            column_positions = [0, a5_width / 2] * ((num_pages + 1) // 2)
            if num_pages % 2:
                column_positions.append(a5_width / 2)
            
            
            a5_canvas.saveState()
            a5_canvas.translate(column_positions[i], 0)
            a5_canvas.scale(scale, scale)
            a5_canvas.doForm(a4_page)
            a5_canvas.restoreState()
            
            if len(a4_page.get_contents().get_object()) > 0:
                bookmarks.append((a4_page.get_contents().get_object()['/Title'], i))
        for title, page_index in bookmarks:
            a5_canvas.addOutlineEntry(title, str(page_index), level=0, closed=None)
        a5_canvas.save()

My goal in pictures:

A4 with columns:
[![enter image description here][1]][1]

Goal:
[![enter image description here][2]][2]

The error I got

```
Traceback (most recent call last):File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 877, in formatreturn pdfdocEnc("%s %s R" % document.idToObjectNumberAndVersion[self.name])KeyError: "FormXob.{'/CropBox': RectangleObject([0, 0, 420.80752613761768543554353527724742889404296875, 595.2755905511811533870059065520763397216796875]), '/Parent': IndirectObject(101, 0, 2653010734384), '/StructParents': 0, '/Contents': {}, '/Rotate': 0, '/MediaBox': RectangleObject([0, 0, 420.80752613761768543554353527724742889404296875, 595.2755905511811533870059065520763397216796875]), '/Resources': {'/ColorSpace': {'/CS0': IndirectObject(1030, 0, 2653010734384)}, '/Font': {'/TT0': IndirectObject(1027, 0, 2653010734384), '/TT1': IndirectObject(1028, 0, 2653010734384), '/TT2': IndirectObject(1029, 0, 2653010734384)}, '/ProcSet': ['/PDF', '/Text'], '/ExtGState': {'/GS0': IndirectObject(1033, 0, 2653010734384)}}, '/Type': '/Page', '/ArtBox': RectangleObject([0, 0, 297.50172046312587781358161009848117828369140625, 420.846827441873529096483252942562103271484375]), '/BleedBox': RectangleObject([0, 0, 297.50172046312587781358161009848117828369140625, 420.846827441873529096483252942562103271484375]), '/TrimBox': RectangleObject([0, 0, 297.50172046312587781358161009848117828369140625, 420.846827441873529096483252942562103271484375])}"
```

```
During handling of the above exception, another exception occurred:
```

```
Traceback (most recent call last):File "E:\Gesichert\Desktop\SpaltenPDF in A5PDF.py", line 77, in <module>a5_canvas.save()File "E:\anaconda\lib\site-packages\reportlab\pdfgen\canvas.py", line 1280, in saveself._doc.SaveToFile(self._filename, self)File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 212, in SaveToFiledata = self.GetPDFData(canvas)File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 238, in GetPDFDatareturn self.format()File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 420, in formatIOf = IO.format(self)File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 867, in formatfcontent = format(self.content, document, toplevel=1)   # yes this is at top levelFile "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 67, in formatf = element.format(document)File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 1023, in formatreturn format(dict, document)File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 67, in formatf = element.format(document)File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 680, in formatL = [(format(PDFName(k),document)+b" "+format(dict[k],document)) for k in keys]File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 680, in <listcomp>L = [(format(PDFName(k),document)+b" "+format(dict[k],document)) for k in keys]File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 67, in formatf = element.format(document)File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 1902, in formatreturn format(DD, document)File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 67, in formatf = element.format(document)File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 680, in formatL = [(format(PDFName(k),document)+b" "+format(dict[k],document)) for k in keys]File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 680, in <listcomp>L = [(format(PDFName(k),document)+b" "+format(dict[k],document)) for k in keys]File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 67, in formatf = element.format(document)File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 680, in formatL = [(format(PDFName(k),document)+b" "+format(dict[k],document)) for k in keys]File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 680, in <listcomp>L = [(format(PDFName(k),document)+b" "+format(dict[k],document)) for k in keys]File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 67, in formatf = element.format(document)File "E:\anaconda\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 879, in formatraise KeyError("forward reference to %s not resolved upon final formatting" % repr(self.name))KeyError: 'forward reference to "FormXob.{'/CropBox': RectangleObject([0, 0, 420.80752613761768543554353527724742889404296875, 595.2755905511811533870059065520763397216796875]), '/Parent': IndirectObject(101, 0, 2653010734384), '/StructParents': 0, '/Contents': {}, '/Rotate': 0, '/MediaBox': RectangleObject([0, 0, 420.80752613761768543554353527724742889404296875, 595.2755905511811533870059065520763397216796875]), '/Resources': {'/ColorSpace': {'/CS0': IndirectObject(1030, 0, 2653010734384)}, '/Font': {'/TT0': IndirectObject(1027, 0, 2653010734384), '/TT1': IndirectObject(1028, 0, 2653010734384), '/TT2': IndirectObject(1029, 0, 2653010734384)}, '/ProcSet': ['/PDF', '/Text'], '/ExtGState': {'/GS0': IndirectObject(1033, 0, 2653010734384)}}, '/Type': '/Page', '/ArtBox': RectangleObject([0, 0, 297.50172046312587781358161009848117828369140625, 420.846827441873529096483252942562103271484375]), '/BleedBox': RectangleObject([0, 0, 297.50172046312587781358161009848117828369140625, 420.846827441873529096483252942562103271484375]), '/TrimBox': RectangleObject([0, 0, 297.50172046312587781358161009848117828369140625, 420.846827441873529096483252942562103271484375])}" not resolved upon final formatting'
```

  [1]: https://i.stack.imgur.com/WpI6g.png
  [2]: https://i.stack.imgur.com/NdHKx.png

**Comment by pubpub-zz** [comment]
first you are using PyPDF2 which is an old version, you have to upgrade to the latests pypdf 3.5.1 (you will have to uninstall PyPDF2 and then install pypdf)

as a test sample here is a code I've just tested:
````
import pypdf
r = pypdf.PdfReader("crazyones.pdf")
w = pypdf.PdfWriter()
#add the pages 4 times using append to get annots....
w.append(r,[0]);w.append(r,[0]);w.append(r,[0]);w.append(r,[0])
#readjust the mediabox
w.pages[0].mediabox.bottom = r.pages[0].mediabox.top - r.pages[0].mediabox.height/2
w.pages[0].mediabox.right = r.pages[0].mediabox.left + r.pages[0].mediabox.width/2
w.pages[1].mediabox.right = w.pages[0].mediabox.right
w.pages[1].mediabox.top = w.pages[0].mediabox.bottom
w.pages[2].mediabox.left = w.pages[0].mediabox.right
w.pages[2].mediabox.bottom = w.pages[0].mediabox.bottom
w.pages[3].mediabox.left = w.pages[2].mediabox.left
w.pages[3].mediabox.top = w.pages[2].mediabox.bottom
w.write("out.pdf")
```

**Comment by MartinThoma** [comment]
@ErfolgreichCharismatisch Does upgrading from PyPDF2 to pypdf solve your issue?

**Comment by pubpub-zz** [comment]
@Martin, can you replace the title with "split page in 4 smaller pages mosaicing" and convert it into a discussion  please
