### ISSUE TITLE
PDFWriter add_page exception. TypeError: unhashable type: 'ArrayObject'

### ISSUE THREAD

**Issue by silan-liu** [py-pdf/pypdf#1705]
PDFWriter add_pages error.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.4.0-144-generic-x86_64-with-glibc2.31

$ python -c "import pypdf;print(pypdf.__version__)"
3.5.1

$ python --version
Python 3.11.1
```

## Code + PDF

```python
from pypdf import PdfReader, PdfWriter

reader = PdfReader("image_t0000000082_n16.pdf")
writer = PdfWriter()
page = reader.pages[0]
writer.add_page(page)  # error occurs here
```

The PDF: [image_t0000000082_n16.pdf](https://github.com/py-pdf/pypdf/files/10949835/image_t0000000082_n16.pdf)

## Traceback

```
Traceback (most recent call last):
  File "/home/moose/Downloads/foo.py", line 6, in <module>
    writer.add_page(page)  # error occurs here
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/moose/Github/py-pdf/pypdf/pypdf/_writer.py", line 356, in add_page
    return self._add_page(page, list.append, excluded_keys)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/moose/Github/py-pdf/pypdf/pypdf/_writer.py", line 301, in _add_page
    page = cast("PageObject", page_org.clone(self, False, excluded_keys))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/moose/Github/py-pdf/pypdf/pypdf/generic/_data_structures.py", line 182, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/home/moose/Github/py-pdf/pypdf/pypdf/generic/_data_structures.py", line 268, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/home/moose/Github/py-pdf/pypdf/pypdf/generic/_data_structures.py", line 182, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/home/moose/Github/py-pdf/pypdf/pypdf/generic/_data_structures.py", line 268, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/home/moose/Github/py-pdf/pypdf/pypdf/generic/_base.py", line 273, in clone
    obj = self.get_object()
          ^^^^^^^^^^^^^^^^^
  File "/home/moose/Github/py-pdf/pypdf/pypdf/generic/_base.py", line 290, in get_object
    obj = self.pdf.get_object(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/moose/Github/py-pdf/pypdf/pypdf/_reader.py", line 1351, in get_object
    retval = read_object(self.stream, self)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/moose/Github/py-pdf/pypdf/pypdf/generic/_data_structures.py", line 1127, in read_object
    return DictionaryObject.read_from_stream(stream, pdf, forced_encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/moose/Github/py-pdf/pypdf/pypdf/generic/_data_structures.py", line 424, in read_from_stream
    if not data.get(key):
           ^^^^^^^^^^^^^
TypeError: unhashable type: 'ArrayObject'
```

**Comment by MartinThoma** [comment]
Interesting. The key is `['/PDF', '/ImageB']`, the value is `['/PDF', '/Text']` and the dictionary is empty.

**Comment by pubpub-zz** [comment]
this PDF file is strongly corrupted.
the error reported here is coded as follow:
6 0 obj.  << [/PDF /ImageB].     [/PDF /Text].  >>.endobj
It declares it as an object but without name field, I can not imagine how to do process it.
this object is not the only corrupted one.

I personnally don't see how to process it : I would recommand to apply some tools to fix it before processing in pypdf

@MartinThoma  your opinion ?

**Comment by MartinThoma** [comment]
It's fine to me to close this as "won't fix".

I was wondering if we should make a help page with hints about how damaged PDF documents can be fixed (e.g. `mutools` / `pikepdf` / `gs`)
