### ISSUE TITLE
"TypeError: unhashable type: 'slice'" when running PdfReader().outline

### ISSUE THREAD

**Issue by Kudalf** [py-pdf/pypdf#1710]
When I try to get the outline of a particular pdf, a TypeError occurred that "TypeError: unhashable type: 'slice'".

## Environment

```bash
$ python -m platform
# Windows-10-10.0.22621-SP0

$ python -c "import pypdf;print(pypdf.__version__)"
# 3.5.2
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
import pypdf

test_book_path = "./irbookonlinereading.pdf"
reader = pypdf.PdfReader(test_book_path)

# Take a look at the original book's outline
print(reader.outline)
```

Here is the [pdf](https://nlp.stanford.edu/IR-book/pdf/irbookonlinereading.pdf) that causes the issue. 
You may add it to the tests~

## Traceback

This is the complete Traceback I see:
```
Traceback (most recent call last):
  File "F:\pycode\bookmark-generator\outline.py", line 7, in <module>
    print(reader.outline)
  File "E:\anaconda3\lib\site-packages\pypdf\_reader.py", line 809, in outline
    return self._get_outline()
  File "E:\anaconda3\lib\site-packages\pypdf\_reader.py", line 838, in _get_outline
    self._namedDests = self._get_named_destinations()
  File "E:\anaconda3\lib\site-packages\pypdf\_reader.py", line 781, in _get_named_destinations
    dest = self._build_destination(k__, val)
  File "E:\anaconda3\lib\site-packages\pypdf\_reader.py", line 980, in _build_destination
    page, typ = array[0:2]  # type: ignore
  File "E:\anaconda3\lib\site-packages\pypdf\generic\_data_structures.py", line 291, in __getitem__
    return dict.__getitem__(self, key).get_object()
TypeError: unhashable type: 'slice'

Process finished with exit code 1
```

**Comment by pubpub-zz** [comment]
@Kudalf 
Thanks for the report. pypdf was not accepting destination stored in "/D" field of DictionaryObjects
I've fixed it. If you are in a rush the mod can be easily copied (have a look at the PR)

**Comment by Kudalf** [comment]
Thank you! It works now.

**Comment by Kudalf** [comment]
The bug is fixed.

**Comment by pubpub-zz** [comment]
we prefer to wait for the PR to merge before closing this issue
