### ISSUE TITLE
pypdf.errors.PdfStreamError: Stream length not defined

### ISSUE THREAD

**Issue by FelipeErmeson** [py-pdf/pypdf#1715]
I can read the pdf normally, but when I try to create a new one by adding the page, it gives an error.

## Environment

```bash
print(pypdf.__version__)"
3.5.2
```

## Code + PDF

Here is the document to reproduce the error:
https://drive.google.com/file/d/15Y96AUD7sCoclk3_n-jLp_YOycaWp-KX/view?usp=sharing

```python
from pypdf import PdfReader, PdfWriter

reader = PdfReader("cf danilo.pdf")
num_pages = len(reader.pages) 
for n in range(num_pages):
    writer = PdfWriter() 
    page = reader.pages[n] 
    writer.add_page(page)
```

## Traceback

```
Traceback (most recent call last):
  File "/.../main.py", line 8, in <module>
    writer.add_page(page)
    ^^^^^^^^^^^^^^^^^^^^^
  File "/.../pypdf/pypdf/_writer.py", line 349, in add_page
    return self._add_page(page, list.append, excluded_keys)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../pypdf/pypdf/_writer.py", line 301, in _add_page
    page = cast("PageObject", page_org.clone(self, False, excluded_keys))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../pypdf/pypdf/generic/_data_structures.py", line 182, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/.../pypdf/pypdf/generic/_data_structures.py", line 268, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/.../pypdf/pypdf/generic/_data_structures.py", line 182, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/.../pypdf/pypdf/generic/_data_structures.py", line 268, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/.../pypdf/pypdf/generic/_data_structures.py", line 182, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/.../pypdf/pypdf/generic/_data_structures.py", line 268, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/.../pypdf/pypdf/generic/_base.py", line 273, in clone
    obj = self.get_object()
          ^^^^^^^^^^^^^^^^^
  File "/.../pypdf/pypdf/generic/_base.py", line 290, in get_object
    obj = self.pdf.get_object(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../pypdf/pypdf/_reader.py", line 1351, in get_object
    retval = read_object(self.stream, self)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../pypdf/pypdf/generic/_data_structures.py", line 1127, in read_object
    return DictionaryObject.read_from_stream(stream, pdf, forced_encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../pypdf/pypdf/generic/_data_structures.py", line 450, in read_from_stream
    raise PdfStreamError("Stream length not defined")
pypdf.errors.PdfStreamError: Stream length not defined
```

**Comment by pubpub-zz** [comment]
@MartinThoma so quick. 
The fix is available for review

@FelipeErmeson 
Your PDF actually is not in accordance with pdf 1.7 specification : Length is normally mandatory.
As Acrobat and other readers are tolerant, I've added so code for tolerance. 
be aware that Warnings will be reported

**Comment by MartinThoma** [comment]
@pubpub-zz Thank you :rocket:

**Comment by MartinThoma** [comment]
The fix by @pubpub-zz was just merged and will be released today in `pypdf > 3.5.2`

**Comment by MartinThoma** [comment]
@FelipeErmeson Thanks for reporting it! If you want, I'll add you to https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html

**Comment by FelipeErmeson** [comment]
Hi @MartinThoma. Glad to have helped, it will be an honor.

**Comment by MartinThoma** [comment]
Done :-) It might take a few minutes until the docs are re-created.
