### ISSUE TITLE
pypdf.errors.PdfReadError: Image data is not rectangular

### ISSUE THREAD

**Issue by BriskyGates** [py-pdf/pypdf#1787]
Hi guys, how are you? First of all thank you so much for making and mantaining this amazing library!
I want to extract all images in the pdf, but failed.
I cannot confirm whether it is inline image or not, I tried to compress the pdf ,then read the orginal instruction sequences, but I couldn't find the 'BI' tag

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Windows-10-10.0.19041-SP0


$ python -c "import pypdf;print(pypdf.__version__)"
3.6.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader

reader = PdfReader("pdf_font_garbled.pdf")
a=reader.pages[1].images
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!
[pdf_font_garbled.pdf](https://github.com/py-pdf/pypdf/files/11219022/pdf_font_garbled.pdf)

## Traceback

This is the complete Traceback I see:

```
Traceback (most recent call last):
  File "D:\code_project\try_pdf\experi\pypdf_image.py", line 15, in <module>
    a=reader.pages[1].images
  File "D:\code_project\venv_all\try_pdf_latest\lib\site-packages\pypdf\_page.py", line 444, in images
    extension, byte_stream = _xobj_to_image(x_object[obj])
  File "D:\code_project\venv_all\try_pdf_latest\lib\site-packages\pypdf\filters.py", line 600, in _xobj_to_image
    data = x_object_obj.get_data()  # type: ignore
  File "D:\code_project\venv_all\try_pdf_latest\lib\site-packages\pypdf\generic\_data_structures.py", line 882, in get_data
    decoded._data = decode_stream_data(self)
  File "D:\code_project\venv_all\try_pdf_latest\lib\site-packages\pypdf\filters.py", line 545, in decode_stream_data
    data = FlateDecode.decode(data, stream.get(SA.DECODE_PARMS))
  File "D:\code_project\venv_all\try_pdf_latest\lib\site-packages\pypdf\filters.py", line 145, in decode
    str_data = FlateDecode._decode_png_prediction(str_data, columns, rowlength)  # type: ignore
  File "D:\code_project\venv_all\try_pdf_latest\lib\site-packages\pypdf\filters.py", line 156, in _decode_png_prediction
    raise PdfReadError("Image data is not rectangular")
pypdf.errors.PdfReadError: Image data is not rectangular
```

**Comment by BriskyGates** [comment]
Hints:
After comparing with pymupdf, it was found that pymupdf fills non-rectangular images with a black background. 
eg.  if a portrait in a PDF is an oval shape, pymupdf will fill it with a black background 

![image_p4_i17](https://user-images.githubusercontent.com/34669414/231687795-7ef0d4b2-544d-4e16-b60d-b815d1071e04.png)
