### ISSUE TITLE
bug : Issues during image extraction

### ISSUE THREAD

**Issue by pubpub-zz** [py-pdf/pypdf#1863]
from @ericgonzadev

### Environment
Mac OS 12.6.6

```
$ python3 -c "import pypdf;print(pypdf.__version__)"
3.9.0
```

### Code + PDF
```
from pypdf import PdfReader
reader = PdfReader(pdf_file)
for index, page in enumerate(reader.pages):
     for img in page.images:
        print(f"{index}-{img.name}")
```

Tested with the following pdf: https://ufile.io/o1whh9b3
The error seems to be happening on page # 34 

### Traceback
```
Traceback (most recent call last):
  File "/Users/eric/Downloads/pdf_extract_images.py", line 60, in scan_directory
    for img in page.images:
                      ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pypdf/_page.py", line 463, in images
    extension, byte_stream = _xobj_to_image(x_object[obj])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pypdf/filters.py", line 707, in _xobj_to_image
    alpha = Image.frombytes("L", size, x_object_obj[G.S_MASK].get_data())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PIL/Image.py", line 2970, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PIL/Image.py", line 826, in frombytes
    raise ValueError(msg)
ValueError: not enough image data
```

_Originally posted by @ericgonzadev in https://github.com/py-pdf/pypdf/issues/1814#issuecomment-1562053211_

**Comment by pubpub-zz** [comment]
for test :  
[o1whh9b3](https://github.com/py-pdf/pypdf/files/11578953/USC.EMBA.-.Pre-Season.and.Theme.I.pdf)

**Comment by pubpub-zz** [comment]
@ericgonzadev
issue created
