### ISSUE TITLE
list index out of range error by extract_text() pf pypdf

### ISSUE THREAD

**Issue by pabst2009** [py-pdf/pypdf#1899]
Replace this: What happened? What were you trying to achieve?

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-4.19.0-24-cloud-amd64-x86_64-with-glibc2.28

$ python -c "import pypdf;print(pypdf.__version__)"
3.10.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader
pdf = "./lv2018tconv.pdf";
pdf = PdfReader(pdf)
for i,page in enumerate(pdf.pages):
  print("i",i,len(pdf.pages));
  page.extract_text();
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

## Traceback

This is the complete Traceback I see:

incorrect startxref pointer(3)
i 0 16
i 1 16
i 2 16
i 3 16
i 4 16
Traceback (most recent call last):
  File "/home/bitnami/dev/webgpt/code/pdfsum.py", line 9, in <module>
    page.extract_text();
    ^^^^^^^^^^^^^^^^^^^
  File "/home/bitnami/dev/webgpt/env/lib/python3.11/site-packages/pypdf/_page.py", line 2159, in extract_text
    return self._extract_text(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/bitnami/dev/webgpt/env/lib/python3.11/site-packages/pypdf/_page.py", line 1804, in _extract_text
    cmaps[f] = build_char_map(f, space_width, obj)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bitnami/dev/webgpt/env/lib/python3.11/site-packages/pypdf/_cmap.py", line 33, in build_char_map
    map_dict, space_code, int_entry = parse_to_unicode(ft, space_code)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bitnami/dev/webgpt/env/lib/python3.11/site-packages/pypdf/_cmap.py", line 211, in parse_to_unicode
    process_rg, process_char, multiline_rg = process_cm_line(
                                             ^^^^^^^^^^^^^^^^
  File "/home/bitnami/dev/webgpt/env/lib/python3.11/site-packages/pypdf/_cmap.py", line 286, in process_cm_line
    multiline_rg = parse_bfrange(line, map_dict, int_entry, multiline_rg)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bitnami/dev/webgpt/env/lib/python3.11/site-packages/pypdf/_cmap.py", line 318, in parse_bfrange
    b = int(lst[1], 16)
            ~~~^^^
IndexError: list index out of range


[lv2018tconv.pdf](https://github.com/py-pdf/pypdf/files/11801077/lv2018tconv.pdf)

**Comment by pubpub-zz** [comment]
i@MartinThoma 
I've tried the test sample but I've got no errors in Python 3.10. Using a PR the error has not been observed neither. Can you try it ?

**Comment by pubpub-zz** [comment]
@pabst2009 
your log reports:
`incorrect startxref pointer(3)`
whereas my run doesn't any message.
can you confirm we are dealing with the same test file

**Comment by pabst2009** [comment]
I confirm that I have no error with the uploaded file.
It seems that pdf was broken by scp in my environment.
