### ISSUE TITLE
UnboundLocalError: cannot access local variable 'img' where it is not associated with a value

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/pypdf#1912]
An UnboundLocalError is thrown when I try to extract (inlined?) images

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.4.0-152-generic-x86_64-with-glibc2.31

$ python -c "import pypdf;print(pypdf.__version__)"
3.11.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader
import pypdf

reader = PdfReader("GeoTopo-komprimiert.pdf")
for page in reader.pages:
    for image in page.images:
        print(image.name)
```

The file: https://github.com/py-pdf/pypdf/files/11845099/GeoTopo-komprimiert.pdf

## Traceback

```
Traceback (most recent call last):
  File "/home/moose/Downloads/size/code.py", line 7, in <module>
    for image in page.images:
  File "/home/moose/Github/py-pdf/pypdf/pypdf/_page.py", line 2555, in __iter__
    yield self[i]
          ~~~~^^^
  File "/home/moose/Github/py-pdf/pypdf/pypdf/_page.py", line 2551, in __getitem__
    return self.get_function(lst[index])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/moose/Github/py-pdf/pypdf/pypdf/_page.py", line 522, in _get_image
    imgd = _xobj_to_image(cast(DictionaryObject, xobjs[id]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/moose/Github/py-pdf/pypdf/pypdf/filters.py", line 852, in _xobj_to_image
    alpha = _xobj_to_image(x_object_obj[IA.S_MASK])[2]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/moose/Github/py-pdf/pypdf/pypdf/filters.py", line 879, in _xobj_to_image
    img.save(img_byte_arr, format=image_format)
    ^^^
UnboundLocalError: cannot access local variable 'img' where it is not associated with a value
```

**Comment by pubpub-zz** [comment]
the issue is due to multiple filters being cascaded. Solution under construction

**Comment by pubpub-zz** [comment]
Note for all: 
there is actually a very limited amount of images within this document : the documents uses many "drawings" (vectorials) such as the torus on the first page which are not images and therefore currently not extracted.

**Comment by rodgermoore** [comment]
https://github.com/py-pdf/pypdf/pull/1913 

Fix worked for me, tnx.
