### ISSUE TITLE
"TypeError: argument of type 'NumberObject' is not iterable" on reader.pages

### ISSUE THREAD

**Issue by jamescrowley** [py-pdf/pypdf#1934]
I'm experimenting with pypdf for text extraction. However, my two PDFs of interest both fail with `"TypeError: argument of type 'NumberObject' is not iterable" on reader.pages` when trying to iterate pages. The code works fine on some other simpler PDFs. Is there any way to get pypdf to successfully run on these PDFs?

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-13.4-arm64-arm-64bit

$ python -c "import pypdf;print(pypdf.__version__)"
3.11.1

$ python --version
Python 3.10.11
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python

reader = PdfReader("test.pdf", strict=False)
text = ""
for page in reader.pages:
    text += page.extract_text()
print(text)
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!

1) https://downloads.ctfassets.net/0oan5gk9rgbh/6TMYLYAcUpjhQpXLDgmdIa/3e1c12d8d827985ef2b4e815a3a6da1f/COVID19_GirlsEducation_corrected_071420.pdf
2) https://gfi.org/wp-content/uploads/2022/03/GFI_Year-in-Review_2021_v2.pdf

## Traceback

This is the complete Traceback I see:

```
Traceback (most recent call last):
  File "/Users/jcrowley/Development/X/test.py", line 9, in <module>
    for page in reader.pages:
  File "/Users/jcrowley/.pyenv/versions/3.10.11/lib/python3.10/site-packages/pypdf/_page.py", line 2455, in __iter__
    for i in range(len(self)):
  File "/Users/jcrowley/.pyenv/versions/3.10.11/lib/python3.10/site-packages/pypdf/_page.py", line 2427, in __len__
    return self.length_function()
  File "/Users/jcrowley/.pyenv/versions/3.10.11/lib/python3.10/site-packages/pypdf/_reader.py", line 452, in _get_num_pages
    self._flatten()
  File "/Users/jcrowley/.pyenv/versions/3.10.11/lib/python3.10/site-packages/pypdf/_reader.py", line 1210, in _flatten
    if PA.TYPE in pages:
TypeError: argument of type 'NumberObject' is not iterable
```

When running with `Strict=True` on document (1) I get

```
Xref table not zero-indexed. ID numbers for objects will be corrected.
Superfluous whitespace found in object header b'xref' b'0'
Traceback (most recent call last):
  File "/Users/jcrowley/Development/X/test.py", line 9, in <module>
    for page in reader.pages:
  File "/Users/jcrowley/.pyenv/versions/3.10.11/lib/python3.10/site-packages/pypdf/_page.py", line 2455, in __iter__
    for i in range(len(self)):
  File "/Users/jcrowley/.pyenv/versions/3.10.11/lib/python3.10/site-packages/pypdf/_page.py", line 2427, in __len__
    return self.length_function()
  File "/Users/jcrowley/.pyenv/versions/3.10.11/lib/python3.10/site-packages/pypdf/_reader.py", line 452, in _get_num_pages
    self._flatten()
  File "/Users/jcrowley/.pyenv/versions/3.10.11/lib/python3.10/site-packages/pypdf/_reader.py", line 1207, in _flatten
    pages = catalog["/Pages"].get_object()  # type: ignore
  File "/Users/jcrowley/.pyenv/versions/3.10.11/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 304, in __getitem__
    return dict.__getitem__(self, key).get_object()
  File "/Users/jcrowley/.pyenv/versions/3.10.11/lib/python3.10/site-packages/pypdf/generic/_base.py", line 295, in get_object
    obj = self.pdf.get_object(self)
  File "/Users/jcrowley/.pyenv/versions/3.10.11/lib/python3.10/site-packages/pypdf/_reader.py", line 1364, in get_object
    f"does not match actual ({idnum} {generation}); "
UnboundLocalError: local variable 'generation' referenced before assignment
```

and on document (2) I get

```
Xref table not zero-indexed. ID numbers for objects will be corrected.
Traceback (most recent call last):
  File "/Users/jcrowley/Development/X/test.py", line 4, in <module>
    reader = PdfReader("GFI_Year-in-Review_2021_v2.pdf", strict=True)
  File "/Users/jcrowley/.pyenv/versions/3.10.11/lib/python3.10/site-packages/pypdf/_reader.py", line 322, in __init__
    self.read(stream)
  File "/Users/jcrowley/.pyenv/versions/3.10.11/lib/python3.10/site-packages/pypdf/_reader.py", line 1541, in read
    self._read_xref_tables_and_trailers(stream, startxref, xref_issue_nr)
  File "/Users/jcrowley/.pyenv/versions/3.10.11/lib/python3.10/site-packages/pypdf/_reader.py", line 1784, in _read_xref_tables_and_trailers
    startxref = self._read_xref_other_error(stream, startxref)
  File "/Users/jcrowley/.pyenv/versions/3.10.11/lib/python3.10/site-packages/pypdf/_reader.py", line 1850, in _read_xref_other_error
    raise PdfReadError("Could not find xref table at specified location")
pypdf.errors.PdfReadError: Could not find xref table at specified location
```

**Comment by jamescrowley** [comment]
Closing - it seems this was Safari doing a terrible job of downloadn the PDF rather than anything else.
