### ISSUE TITLE
Read metadata Error: CreationDate & ModDate

### ISSUE THREAD

**Issue by portfedh** [py-pdf/pypdf#1943]
I am trying to read the creation and modification date metadata of a pdf. 

This is the code:
```
from PyPDF2 import PdfReader
reader = PdfReader("example.pdf")
meta = reader.metadata
```

And got the following output:

` {'/Title': 'Microsoft PowerPoint - ByAllAccounts_Pitch_Deck_DataFeeds_120522', '/Producer': 'macOS Version 12.6.7 (Build 21G651) Quartz PDFContext', '/Author': 'pmiller', '/CreationDate': "D:20230705005151Z00'00'", '/ModDate': "D:20230705005151Z00'00'"}.`

However when I run the following code on the metadata:
`print(f"Creation date: {meta.creation_date}.")`

I get the following error:

```
Traceback (most recent call last):
  File "/Users/portfedh/Dropbox (Personal)/Coding/2_Projects/AnaOCR/read_metadata.py", line 10, in <module>
    print(f"Creation date: {meta.creation_date}. \n")
  File "/Users/portfedh/Dropbox (Personal)/Coding/2_Projects/AnaOCR/venv/lib/python3.10/site-packages/PyPDF2/_reader.py", line 244, in creation_date
    return datetime.strptime(text.replace("'", ""), "D:%Y%m%d%H%M%S%z")
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/_strptime.py", line 352, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: 0000
```

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
# macOS-12.6.7-x86_64-i386-64bit

$ python -c "import pypdf;print(pypdf.__version__)"
# 3.0.1
```

**Comment by MartinThoma** [comment]
PyPDF2 is deprecated. Use pypdf.


The following also cannot be, because that version of pypdf doesn't exist:
```
$ python -c "import pypdf;print(pypdf.__version__)"
# 3.0.1
````

**Comment by pubpub-zz** [comment]
I've tested it with latest release and it is failing. Oddly the UTC time format (with Z) has not been tested.
PR is produced
