### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'size'

### ISSUE THREAD

**Issue by mnmtz** [py-pdf/pypdf#1986]
Error raised when iterating through the images of the first page.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-13.4.1-arm64-arm-64bit

$ python -c "import pypdf;print(pypdf.__version__)"
3.12.2
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
reader = PdfReader(file, strict=False)
writer = PdfWriter()

writer.clone_document_from_reader(reader)

for page in writer.pages:

     for img_obj in page.images:
          img_count += 1
```

Sample PDF:
[example_038.pdf](https://github.com/py-pdf/pypdf/files/12102958/example_038.pdf)

## Traceback

This is the complete Traceback I see:

```
Traceback (most recent call last):
  File "/Users/mickey/Documents/GitHub/neuralPDF/Scripts/Compress_PDF_pypdf.py", line 443, in <module>
    compress_pdf()
  File "/Users/mickey/Documents/GitHub/neuralPDF/Scripts/Compress_PDF_pypdf.py", line 363, in compress_pdf
    img_num += process_page(page, page_num, preset, device)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mickey/Documents/GitHub/neuralPDF/Scripts/Compress_PDF_pypdf.py", line 26, in process_page
    for img_obj in page.images:
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pypdf/_page.py", line 2604, in __iter__
    yield self[i]
          ~~~~^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pypdf/_page.py", line 2600, in __getitem__
    return self.get_function(lst[index])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pypdf/_page.py", line 522, in _get_image
    imgd = _xobj_to_image(cast(DictionaryObject, xobjs[id]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pypdf/filters.py", line 929, in _xobj_to_image
    if img.size != alpha.size:
                   ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'size'
```

**Comment by pubpub-zz** [comment]
The image on the first page of your file shows unusual image size (16000x16000 => 244 M pixels = 976 MB with 32 bits RGBA). The alpha image/layer can not be processed in pillow with changing the parameters. You have to add at the beginning of your code:
```
from PIL import Image
Image.MAX_IMAGE_PIXELS = 1024**3
```

Even after Pillow and other programs has some troubles to process them. 
(note : Acrobat reader did process it but not PDF.js)

**Comment by MartinThoma** [comment]
WTF. 1024**3 pixels means 32768**2 pixels. Why is the resolution that extreme?

Also interesting that the Chrome PDF viewer can deal with that (although being slow... but that is understandable)

**Comment by MartinThoma** [comment]
> Please don't ask why they are not able to resize/compress the pictures

I feel your pain :smile: During my software engineering career I often had the feeling that way too much of the business world relies on PDF and Excel :smile:
