### ISSUE TITLE
NotImplementedError: unsupported filter /RunLengthDecode

### ISSUE THREAD

**Issue by stefan6419846** [py-pdf/pypdf#2011]
## Explanation

The RunLengthDecode filter does not seem to be implemented.

It seems like a corresponding example file is very easy to create by just running ImageMagick on a PDF file of your choice: `convert -density 300 -units PixelsPerInch test_document.pdf -alpha off out.pdf` (example: [out.pdf](https://github.com/py-pdf/pypdf/files/12159941/out.pdf))

## Code Example

```python3
reader = PdfReader('tmp/out.pdf')
page = reader.pages[0]
for image in page.images:
    print(image)
```

```python3    
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/user/lib/python3.9/site-packages/pypdf/_page.py", line 2604, in __iter__
    yield self[i]
  File "/home/user/lib/python3.9/site-packages/pypdf/_page.py", line 2600, in __getitem__
    return self.get_function(lst[index])
  File "/home/user/lib/python3.9/site-packages/pypdf/_page.py", line 522, in _get_image
    imgd = _xobj_to_image(cast(DictionaryObject, xobjs[id]))
  File "/home/user/lib/python3.9/site-packages/pypdf/filters.py", line 854, in _xobj_to_image
    data = x_object_obj.get_data()  # type: ignore
  File "/home/user/lib/python3.9/site-packages/pypdf/generic/_data_structures.py", line 956, in get_data
    decoded._data = decode_stream_data(self)
  File "/home/user/lib/python3.9/site-packages/pypdf/filters.py", line 634, in decode_stream_data
    raise NotImplementedError(f"unsupported filter {filter_type}")
NotImplementedError: unsupported filter /RunLengthDecode
```

**Comment by pubpub-zz** [comment]
to force RunLengthDecode you should add `-compress RLE`
however thanks for report and test set:
the image (for test):
![RL](https://github.com/py-pdf/pypdf/assets/4083478/6d63972e-a3d6-4cf9-aa6f-0793af24cded)

**Comment by pubpub-zz** [comment]
@stefan6419846 PR is available if you want to test it

**Comment by stefan6419846** [comment]
@pubpub-zz Just did a quick test with my original failing file and it seems to work correctly. Thanks.
