### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by grumpyp** [py-pdf/pypdf#2098]
Hi, I am building an API with Django and trying to save `.pdf` files to an Azure Blob Storage.

## Environment

`Python 3.11.4`
`pypdf==3.15.1`

## Code + PDF
The pdf is just an example file which I use to develop the API.

minimal example
```
from pypdf import PdfReader
print(type(uploaded_file))

reader = PdfReader(uploaded_file)
print(reader.pages[0].extract_text())
```

type: `[<class 'django.core.files.uploadedfile.InMemoryUploadedFile'>`

## Traceback

```
...
Object 1 0 not defined.
Overwriting cache for 0 1
Object 1 0 not defined.
Overwriting cache for 0 1
Object 1 0 not defined.
Internal Server Error: /api/db/
Traceback (most recent call last):
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/aixplora_cloud/aixplora_cloud/api/views.py", line 173, in post
    print(reader.pages[0].extract_text())
          ~~~~~~~~~~~~^^^
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/pypdf/_page.py", line 2494, in __getitem__
    len_self = len(self)
               ^^^^^^^^^
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/pypdf/_page.py", line 2475, in __len__
    return self.length_function()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/pypdf/_reader.py", line 448, in _get_num_pages
    self._flatten()
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/pypdf/_reader.py", line 1233, in _flatten
    self._flatten(page.get_object(), inherit, **addt)
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/pypdf/_reader.py", line 1233, in _flatten
    self._flatten(page.get_object(), inherit, **addt)
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/pypdf/_reader.py", line 1233, in _flatten
    self._flatten(page.get_object(), inherit, **addt)
  [Previous line repeated 936 more times]
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/pypdf/generic/_base.py", line 307, in get_object
    obj = self.pdf.get_object(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/pypdf/_reader.py", line 1440, in get_object
    self.cache_indirect_object(
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/pypdf/_reader.py", line 1518, in cache_indirect_object
    logger_warning(msg, __name__)
  File "/Users/patrickgerard/Documents/GitHub/aixplora-cloud/venv/lib/python3.11/site-packages/pypdf/_utils.py", line 450, in logger_warning
    logging.getLogger(src).warning(msg)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1501, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1714, in callHandlers
    lastResort.handle(record)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 688, in format
    if self.usesTime():
       ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 656, in usesTime
    return self._style.usesTime()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 433, in usesTime
    return self._fmt.find(self.asctime_search) >= 0
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by grumpyp** [comment]
I've resolved the issue. I realized that after using .read() on a file, the pointer is positioned at the end, which means subsequent reads show the file as empty. However, I'm still uncertain if this behavior is the intended one.

**Comment by MartinThoma** [comment]
An endless loop is never intended. Thanks for reporting!

**Comment by pubpub-zz** [comment]
I'm confused. I've used the following code:
```
f=open("outxxx.pdf","rb")
r=pypdf.PdfReader(f)
r=pypdf.PdfReader(f)
len(r.pages)  
# returns 1
r.pages[0].extract_text()
# returns "" as expected
```
without issues. Is the problem within pypdf or  in the way <class 'django.core.files.uploadedfile.InMemoryUploadedFile'> is used ?

**Comment by pubpub-zz** [comment]
@MartinThoma 
this issue does not seem to be linked with pypdf, we should close it

**Comment by stefan6419846** [comment]
Apparently, the buffer is at the end in this case and crashes *pypdf*, which seems to be a bug on our side as well.

**Comment by pubpub-zz** [comment]
> Apparently, the buffer is at the end in this case and crashes *pypdf*, which seems to be a bug on our side as well.

@stefan6419846 , @grumpyp  can you produce a simple test case. Mine was working

**Comment by stefan6419846** [comment]
In theory, this should not be related to a PDF file. Nevertheless, I could not reproduce this with a basic `StringIO` buffer for now as well as when feeding `StringIO` into an `InMemoryUploadedFile` and calling `read()` before creating the `PdfReader` - neither on an older PyPDF 3.13.0 nor on 3.15.4. Let's wait for @grumpyp to report on this again if this can actually be reproduced independently.

**Comment by pubpub-zz** [comment]
@grumpyp  +1?

**Comment by grumpyp** [comment]
Hi guys,

to be honest I don't know how to really reproduce it.

So what I do is I upload a file, send it to FastAPI handle it there and send it to Django.


I could probably do something like

```
curl -X POST \
         -H "Content-Type: multipart/form-data" \
         -F "file=@/tmp/file.pdf" \
```

```
files = request.FILES.getlist('file')
..
data = {
                        'uploaded_file': uploaded_file,
                        'file_name': uploaded_file.name,
                        'file_type': uploaded_file.content_type,
                        'file_size': uploaded_file.size
                    }
transcription = FILE_HANDLERS[file_extension](uploaded_file)
...
```

Which then executes the initial exemple in `transcription`.


Can't give anymore feedback on this. Good luck guys, other than that if it's a bug someone else will come and adress it again.

**Comment by pubpub-zz** [comment]
without more data,  I think we have to close it as not reproduced.
If someone meet the problem we will reopen it
