### ISSUE TITLE
BUG: Infinite recursion bug with PSUtils

### ISSUE THREAD

**Issue by rrthomas** [py-pdf/pypdf#2102]
This bug reports originates with pspdfutils: See rrthomas/psutils#57.

The command `psnup -2 testbook.pdf output.pdf` gives an infinite recursion backtrace.

## Environment

Ubuntu 22.04.

```bash
$ python -m platform
Linux-6.2.0-26-generic-x86_64-with-glibc2.35

$ python -c "import pypdf;print(pypdf.__version__)"
3.15.2
```

## Code + PDF

Minimal example:

```python
from pypdf import PdfWriter, PdfReader

reader = PdfReader("testbook.pdf")
writer = PdfWriter("foo.pdf")

width, height = 595, 841

outpage = writer.add_blank_page(width, height)
outpage.merge_page(reader.pages[6])
```

Note in particular: if I replace the last two lines with

```
outpage = writer.add_page(reader.pages[6])
```

then it works.

Here is the test file:

[testbook.pdf](https://github.com/py-pdf/pypdf/files/12389243/testbook.pdf)

## Traceback

This is the complete Traceback I see:

```
$ python test.py
Traceback (most recent call last):
  File "/home/rrt/Software/psutils/test.py", line 9, in <module>
    outpage.merge_page(reader.pages[6])
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/_page.py", line 1044, in merge_page
    self._merge_page(page2, over=over, expand=expand)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/_page.py", line 1071, in _merge_page
    return self._merge_page_writer(
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/_page.py", line 1224, in _merge_page_writer
    aa = a.clone(
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 197, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 297, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 197, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 297, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 115, in clone
    arr.append(data.clone(pdf_dest, force_duplicate, ignore_fields))
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_base.py", line 295, in clone
    obj.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 197, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
```

then repeats a lot, before ending:

```
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_base.py", line 295, in clone
    obj.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 197, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 297, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 115, in clone
    arr.append(data.clone(pdf_dest, force_duplicate, ignore_fields))
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 197, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 297, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 197, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 297, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 115, in clone
    arr.append(data.clone(pdf_dest, force_duplicate, ignore_fields))
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_base.py", line 295, in clone
    obj.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 197, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 289, in _clone
    if isinstance(v, StreamObject):
  File "/usr/lib/python3.10/typing.py", line 1503, in __instancecheck__
    issubclass(instance.__class__, cls)):
  File "/usr/lib/python3.10/abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
RecursionError: maximum recursion depth exceeded in comparison
```

Thanks very much for pypdf!

**Comment by rrthomas** [comment]
See rrthomas/psutils#57.

**Comment by rrthomas** [comment]
The end of the stack trace also seems important, if not more so:

```
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 197, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 297, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 197, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 297, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 115, in clone
    arr.append(data.clone(pdf_dest, force_duplicate, ignore_fields))
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_base.py", line 295, in clone
    obj.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 197, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 297, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 115, in clone
    arr.append(data.clone(pdf_dest, force_duplicate, ignore_fields))
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 197, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 297, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 197, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 297, in _clone
    v.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 115, in clone
    arr.append(data.clone(pdf_dest, force_duplicate, ignore_fields))
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_base.py", line 295, in clone
    obj.clone(pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 197, in clone
    d__._clone(self, pdf_dest, force_duplicate, ignore_fields)
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 296, in _clone
    self[NameObject(k)] = (
  File "/home/rrt/.local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 306, in __setitem__
    if not isinstance(key, PdfObject):
  File "/usr/lib/python3.10/typing.py", line 1503, in __instancecheck__
    issubclass(instance.__class__, cls)):
  File "/usr/lib/python3.10/abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by pubpub-zz** [comment]
the issue is due to the link to the page note and vice-versa which is disturbing the merge function. 
the only solution I imagine would be to discard all annotations, article, and so one but this may remove capabilities that may be useful for other users.

Is there any reason you are trying to merge theses pages onto another page ? Can't it be done in the other way ?🤔

**Comment by rrthomas** [comment]
The `psnup` command takes N pages of its input PDF file and puts them on to one page of its output (often called "n-up" printing). I'm not aware of another way of doing this with pypdf, but would be open to suggestions.

In general, this is quite a surprising result: I would expect pages to be self-contained, so that combining them wouldn't be a problem; but there may be complexities to PDF of which I'm not aware. (psutils in the past only worked with PostScript files.) If there's no reasonable solution, then I guess this situation should be detected so that it's possible to work with arbitrary PDF files without having this sort of stack exhaustion problem?

**Comment by pubpub-zz** [comment]
I will leave the night over. maybe some ideas will come...😶‍😴

**Comment by pubpub-zz** [comment]
The issue being because of the links,
this is a proposal
```
import pypdf
from io import BytesIO
w = pypdf.PdfWriter(clone_from="e:/Downloads/testbook.pdf")
w.remove_links()
b=BytesIO()
w.write(b)
r=pypdf.PdfReader(b)
ww = pypdf.PdfWriter()
p=ww.add_blank_page(595,841)
p.merge_page(r.pages[6])
ww.write("out.pdf")
```
out.pdf is good then, but links are lost. Sorry

**Comment by rrthomas** [comment]
Thanks, that's a useful workaround. However, surely this is still a bug in pypdf: I understand that it may not be possible to do what I'm doing, but it shouldn't crash? If I can detect the situation, I could conceivably remove links when they wouldn't work, but otherwise keep them.

Also, I'm sorry, I don't really understand what the issue is here; I'd be very grateful if you could explain further, if possible.

**Comment by rrthomas** [comment]
> ```
> import pypdf
> from io import BytesIO
> w = pypdf.PdfWriter(clone_from="e:/Downloads/testbook.pdf")
> w.remove_links()
> b=BytesIO()
> w.write(b)
> r=pypdf.PdfReader(b)
> ww = pypdf.PdfWriter()
> p=ww.add_blank_page(595,841)
> p.merge_page(r.pages[6])
> ww.write("out.pdf")
> ```

I tried this code, and I get an output file with a single blank page. But, the input page 7 (i.e. index 6) is not blank. Also, the output file is 53KB long. (This is with pypdf 3.15.2.) I can't see anything wrong with the code…

**Comment by pubpub-zz** [comment]
I've rerun the copied test and this is the output:
[out.pdf](https://github.com/py-pdf/pypdf/files/12505500/out.pdf)
It looks ok for me

**Comment by rrthomas** [comment]
Thanks. I don't know what happened, as the file you uploaded is identical to the one I produced, and now both look fine in  Evince.

**Comment by rrthomas** [comment]
Fantastic work, @MartinThoma! I looked into this bug myself earlier in the week, but didn't manage to make a serious attempt at it.

**Comment by MartinThoma** [comment]
All the credit goes to @exiledkingcc :-)

**Comment by MartinThoma** [comment]
I'm re-opening this so that I don't forget to write a security notice

**Comment by rrthomas** [comment]
Thanks very much, @exiledkingcc!

**Comment by MartinThoma** [comment]
I've just noticed that this gives `RecursionError: maximum recursion depth exceeded` and not an infinite loop. For this reason, I don't think it is security relevant :tada:

**Comment by pubpub-zz** [comment]
Based on your comment I close it (to clean up the database)
