### ISSUE TITLE
Too Many Values to Unpack in Python error in code __data_structures.py

### ISSUE THREAD

**Issue by davinascimento84** [py-pdf/pypdf#2210]
When I was merging pdf files with PdfMerger, I got a error of too many values to unpackk in the _data_structures.py file. The point of code was (about 1260 line in 3.0.version of PyPDF2)

        # from table 8.2 of the PDF 1.7 reference.
        if typ == "/XYZ":
            (
                self[NameObject(TA.LEFT)],
                self[NameObject(TA.TOP)],
                self[NameObject("/Zoom")],
            ) = args

## Environment

python 3.10.12 on linux Ubuntu

Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

## Code + PDF

The PDF has sensitive information and can not be upload to here.
The codes goes like this:

    def concat_pdf_files(self, pdf_files, output_filename):
        try:
            pdf_merger = PyPDF2.PdfMerger()
            for arquivo in pdf_files:
                with open(arquivo, 'rb') as pdf_file:
                    print(f"Adicionando {arquivo} à concatenação")
                    pdf_reader = PyPDF2.PdfReader(pdf_file)
                    pdf_merger.append(pdf_reader)

            output_path = os.path.join(self.output_folder, output_filename)
            print(f"Concatenando em {output_path}")
            pdf_merger.write(output_path)
        except Exception as e:
            self.logger.lprint(e)
            self.logger.lprint_error(e)
            print(type(e))

```python
# TODO: Your code goes here
```

## Traceback

```
Traceback (most recent call last):
  File "/mnt/c/wsl_workspace/preparacao/bli.py", line 16, in <module>
    concat_pdf_files(['A.pdf', 'E.pdf'], 'saida_pdf.pdf')
  File "/mnt/c/wsl_workspace/preparacao/bli.py", line 10, in concat_pdf_files
    pdf_merger.append(pdf_reader)
  File "/home/davi/.local/lib/python3.10/site-packages/PyPDF2/_utils.py", line 417, in wrapper
    return func(*args, **kwargs)
  File "/home/davi/.local/lib/python3.10/site-packages/PyPDF2/_merger.py", line 319, in append
    self.merge(len(self.pages), fileobj, outline_item, pages, import_outline)
  File "/home/davi/.local/lib/python3.10/site-packages/PyPDF2/_utils.py", line 417, in wrapper
    return func(*args, **kwargs)
  File "/home/davi/.local/lib/python3.10/site-packages/PyPDF2/_merger.py", line 217, in merge
    outline = reader.outline
  File "/home/davi/.local/lib/python3.10/site-packages/PyPDF2/_reader.py", line 745, in outline
    return self._get_outline()
  File "/home/davi/.local/lib/python3.10/site-packages/PyPDF2/_reader.py", line 774, in _get_outline
    self._namedDests = self._get_named_destinations()
  File "/home/davi/.local/lib/python3.10/site-packages/PyPDF2/_reader.py", line 717, in _get_named_destinations
    dest = self._build_destination(k__, val)
  File "/home/davi/.local/lib/python3.10/site-packages/PyPDF2/_reader.py", line 906, in _build_destination
    return Destination(title, page, Fit(fit_type=typ, fit_args=array))  # type: ignore
  File "/home/davi/.local/lib/python3.10/site-packages/PyPDF2/generic/_data_structures.py", line 1256, in __init__
    (
ValueError: too many values to unpack (expected 3)
```

**Comment by davinascimento84** [comment]
I Worked around just putting a limit to the list, liked code below:

        # from table 8.2 of the PDF 1.7 reference.
        if typ == "/XYZ":
            (
                self[NameObject(TA.LEFT)],
                self[NameObject(TA.TOP)],
                self[NameObject("/Zoom")],
            ) = args**[:3]**

**Comment by pubpub-zz** [comment]
From my understanding 
a)you are using PyPDF2 which is bon more supposed: please replace it with pypdf
b) PdfMerger is obsolete please use PdfWriter

**Comment by pubpub-zz** [comment]
I close it as dealing with PyPDF2 and PdfMerger

if the error is still present after upgrade feel free to ask for reopening it
