### ISSUE TITLE
AttributeError: 'DictionaryObject' object has no attribute 'insert_child'

### ISSUE THREAD

**Issue by Firestar-Reimu** [py-pdf/pypdf#2233]
I use pypdf 3.16.2/python 3.11.5 on conda-forge on Archlinux

I want to add bookmarks to this pdf (13MB): https://paste.c-net.org/TexasGander

using the code below:

```python
import re
import sys

from os.path import exists, splitext
from pypdf import PdfReader, PdfWriter


def _get_parent_bookmark(current_indent, history_indent, bookmarks):
    """The parent of A is the nearest bookmark whose indent is smaller than A's"""
    assert len(history_indent) == len(bookmarks)
    if current_indent == 0:
        return None
    for i in range(len(history_indent) - 1, -1, -1):
        # len(history_indent) - 1   ===>   0
        if history_indent[i] < current_indent:
            return bookmarks[i]
    return None


def addBookmark(pdf_path, bookmark_txt_path, page_offset):
    if not exists(pdf_path):
        return "Error: No such file: {}".format(pdf_path)
    if not exists(bookmark_txt_path):
        return "Error: No such file: {}".format(bookmark_txt_path)

    with open(bookmark_txt_path, "r", encoding="utf-8") as f:
        bookmark_lines = f.readlines()
    reader = PdfReader(pdf_path)
    writer = PdfWriter()
    writer.clone_document_from_reader(reader)

    maxPages = len(reader.pages)
    bookmarks, history_indent = [], []
    # decide the level of each bookmark according to the relative indent size in each line
    #   no indent:          level 1
    #     small indent:     level 2
    #       larger indent:  level 3
    #   ...
    for line in bookmark_lines:
        line2 = re.split(r"\s+", line.strip())
        if len(line2) == 1:
            continue

        indent_size = len(line) - len(line.lstrip())
        parent = _get_parent_bookmark(indent_size, history_indent, bookmarks)
        print(parent)
        history_indent.append(indent_size)

        title, page = " ".join(line2[:-1]), int(line2[-1]) - 1
        if page + page_offset >= maxPages:
            return "Error: page index out of range: %d >= %d" % (page + page_offset, maxPages)
        new_bookmark = writer.add_outline_item(title, page + page_offset, parent=parent)
        # AttributeError: 'DictionaryObject' object has no attribute 'insert_child'
        print("new_bookmark")
        bookmarks.append(new_bookmark)

    out_path = splitext(pdf_path)[0] + "-new.pdf"
    with open(out_path, "wb") as f:
        writer.write(f)

    return "The bookmarks have been added to %s" % out_path


if __name__ == "__main__":
    import sys

    args = sys.argv
    if len(args) != 4:
        print("Usage: %s [pdf] [bookmark_txt] [page_offset]" % args[0])
    else:
        print(addBookmark(args[1], args[2], int(args[3])))

# python bookmarks.py "/path/to/xxx.pdf" "/path/to/toc.txt" page_offset
```

`toc.txt` is here: https://paste.c-net.org/HeraldCreated

**Comment by Firestar-Reimu** [comment]
PS: I don't know why use `add_outline_item` intead of `add_bookmark`, `bookmark` is a more common word.

**Comment by Firestar-Reimu** [comment]
A good example is this:

[Canon_in_D_Violin_Piano.pdf](https://github.com/py-pdf/pypdf/files/12779501/Canon_in_D_Violin_Piano.pdf)

```
1 Canon 1
        1.1 Canon 2
2 Canon 3
        2.1 Canon 3
```

which returns:

```
$ python bookmarks.py Canon_in_D_Violin_Piano.pdf canon.txt 0
None
new_bookmark
IndirectObject(54, 0, 140018588424784)
new_bookmark
None
new_bookmark
IndirectObject(58, 0, 140018588424784)
new_bookmark
The bookmarks have been added to Canon_in_D_Violin_Piano-new.pdf
```

**Comment by Firestar-Reimu** [comment]
It seems that it is because the original pdf has [page_labels](https://pypdf.readthedocs.io/en/stable/modules/PdfWriter.html?highlight=set_page_label#pypdf.PdfWriter.set_page_label)

**Comment by stefan6419846** [comment]
Do we really need this much example code? Do you have a way to reduce it into a standalone example with the minimal code to actually reproduce this issue?

**Comment by pubpub-zz** [comment]
@Firestar-Reimu 
at least please provide the error stack.

**Comment by Firestar-Reimu** [comment]
It was here, sorry that I mis-deleted that:

```
$ python bookmarks.py test.pdf toc.txt 13
None
Traceback (most recent call last):
  File "/home/firestar/Documents/bookmarks.py", line 70, in <module>
    print(addBookmark(args[1], args[2], int(args[3])))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/firestar/Documents/bookmarks.py", line 51, in addBookmark
    new_bookmark = writer.add_outline_item(title, page + page_offset, parent=parent)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/firestar/.miniconda/lib/python3.11/site-packages/pypdf/_writer.py", line 1912, in add_outline_item
    return self.add_outline_item_destination(outline_item, parent, before, is_open)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/firestar/.miniconda/lib/python3.11/site-packages/pypdf/_writer.py", line 1741, in add_outline_item_destination
    parent.insert_child(
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'DictionaryObject' object has no attribute 'insert_child'
```

**Comment by MartinThoma** [comment]
@Firestar-Reimu What the others wanted to point you to is called an [MCVE (minimal, complete and verifiable example)](https://stackoverflow.com/help/minimal-reproducible-example).

You might now know which line causes the issue, but you can figure it out. Comment one line out, run the code. Does it still show the issue? Then it is not necessary for this ticket.

Doing so inceases your chance that people will investigate your issue.

**Comment by pubpub-zz** [comment]
pdf for test:
[test-12.pdf](https://github.com/py-pdf/pypdf/files/12797067/test-12.pdf)

**Comment by pubpub-zz** [comment]
your pdf has an outlines entry in the root that exists but which is "empty". This is inducing some type issue. the PR should fix this
