### ISSUE TITLE
Global Name Error RecursionError in PyPDF2

### ISSUE THREAD

**Issue by shendypj18** [py-pdf/pypdf#2283]
I got this error when i used PyPDF2 in Python 2.7

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Darwin-22.1.0-x86_64-i386-64bit

$ python -V
Python 2.7.18 :: Anaconda, Inc.

$ python -c "import PyPDF2 ;print(PyPDF2.__version__)" 
1.28.6
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
    if newobj is None:
                    try:
                        newobj = data.pdf.get_object(data)
                        self._objects.append(None)  # placeholder
                        idnum = len(self._objects)
                        newobj_ido = IndirectObject(idnum, 0, self)
                        if data.pdf not in extern_map:
                            extern_map[data.pdf] = {}
                        if data.generation not in extern_map[data.pdf]:
                            extern_map[data.pdf][data.generation] = {}
                        extern_map[data.pdf][data.generation][data.idnum] = newobj_ido
                        newobj = self._sweep_indirect_references(extern_map, newobj)
                        self._objects[idnum - 1] = newobj
                        return newobj_ido
                    except (ValueError, RecursionError): 
                        # Unable to resolve the Object, returning NullObject instead.
                        warnings.warn(
                            "Unable to resolve [{}: {}], returning NullObject instead".format(
                                data.__class__.__name__, data
                            )
                        )
                        return NullObject()
                return newobj
```

## Traceback

This is the complete Traceback I see:

```
Traceback (most recent call last):
  File "/Users/shendy.juniantotunasgroup.com/Deployment/Odoo/base/tdm_odoo10/odoo/http.py", line 686, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/shendy.juniantotunasgroup.com/Deployment/Odoo/base/tdm_odoo10/odoo/http.py", line 723, in dispatch
    result = self._call_function(**self.params)
  File "/Users/shendy.juniantotunasgroup.com/Deployment/Odoo/base/tdm_odoo10/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/shendy.juniantotunasgroup.com/Deployment/Odoo/base/tdm_odoo10/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/shendy.juniantotunasgroup.com/Deployment/Odoo/base/tdm_odoo10/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/shendy.juniantotunasgroup.com/Deployment/Odoo/base/tdm_odoo10/odoo/http.py", line 981, in __call__
    return self.method(*args, **kw)
  File "/Users/shendy.juniantotunasgroup.com/Deployment/Odoo/base/tdm_odoo10/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/Users/shendy.juniantotunasgroup.com/Deployment/Odoo/base/tdm_odoo10/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/Users/shendy.juniantotunasgroup.com/Deployment/Odoo/base/tdm_odoo10/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/shendy.juniantotunasgroup.com/Deployment/Odoo/base/tdm_odoo10/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/Users/shendy.juniantotunasgroup.com/Deployment/Odoo/base/tdm_odoo10/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/Users/shendy.juniantotunasgroup.com/Deployment/Odoo/custom-addons/asp_dms_addons/dms_proposal/models/dms_proposal.py", line 672, in action_print_proposal
    merge_pdf.write(merged_pdf_file)
  File "/Users/shendy.juniantotunasgroup.com/opt/miniconda3/envs/py2/lib/python2.7/site-packages/PyPDF2/merger.py", line 264, in write
    self.output.write(fileobj)
  File "/Users/shendy.juniantotunasgroup.com/opt/miniconda3/envs/py2/lib/python2.7/site-packages/PyPDF2/_writer.py", line 719, in write
    self._sweep_indirect_references(external_reference_map, self._root)
  File "/Users/shendy.juniantotunasgroup.com/opt/miniconda3/envs/py2/lib/python2.7/site-packages/PyPDF2/_writer.py", line 825, in _sweep_indirect_references
    self._sweep_indirect_references(extern_map, realdata)
  File "/Users/shendy.juniantotunasgroup.com/opt/miniconda3/envs/py2/lib/python2.7/site-packages/PyPDF2/_writer.py", line 801, in _sweep_indirect_references
    value = self._sweep_indirect_references(extern_map, value)
  File "/Users/shendy.juniantotunasgroup.com/opt/miniconda3/envs/py2/lib/python2.7/site-packages/PyPDF2/_writer.py", line 825, in _sweep_indirect_references
    self._sweep_indirect_references(extern_map, realdata)
  File "/Users/shendy.juniantotunasgroup.com/opt/miniconda3/envs/py2/lib/python2.7/site-packages/PyPDF2/_writer.py", line 801, in _sweep_indirect_references
    value = self._sweep_indirect_references(extern_map, value)
  File "/Users/shendy.juniantotunasgroup.com/opt/miniconda3/envs/py2/lib/python2.7/site-packages/PyPDF2/_writer.py", line 810, in _sweep_indirect_references
    value = self._sweep_indirect_references(extern_map, data[i])
  File "/Users/shendy.juniantotunasgroup.com/opt/miniconda3/envs/py2/lib/python2.7/site-packages/PyPDF2/_writer.py", line 825, in _sweep_indirect_references
    self._sweep_indirect_references(extern_map, realdata)
  File "/Users/shendy.juniantotunasgroup.com/opt/miniconda3/envs/py2/lib/python2.7/site-packages/PyPDF2/_writer.py", line 801, in _sweep_indirect_references
    value = self._sweep_indirect_references(extern_map, value)
  File "/Users/shendy.juniantotunasgroup.com/opt/miniconda3/envs/py2/lib/python2.7/site-packages/PyPDF2/_writer.py", line 801, in _sweep_indirect_references
    value = self._sweep_indirect_references(extern_map, value)
  File "/Users/shendy.juniantotunasgroup.com/opt/miniconda3/envs/py2/lib/python2.7/site-packages/PyPDF2/_writer.py", line 801, in _sweep_indirect_references
    value = self._sweep_indirect_references(extern_map, value)
  File "/Users/shendy.juniantotunasgroup.com/opt/miniconda3/envs/py2/lib/python2.7/site-packages/PyPDF2/_writer.py", line 851, in _sweep_indirect_references
    except (ValueError, RecursionError):
NameError: global name 'RecursionError' is not defined
```

**Comment by pubpub-zz** [comment]
PyPDF2 is no more maintained. Please change to pypdf.

**Comment by stefan6419846** [comment]
Python 2.7 is EOL as well.

**Comment by MartinThoma** [comment]
I'm closing this issue now as 

1. PyPDF2 and Python 2.7 are deprecated
2. The example is not complete.

If/when those points are addressed, we can re-open.
