### ISSUE TITLE
IndirectObject warnings from PdfReader#pages result in width of 0.0

### ISSUE THREAD

**Issue by SamStephens** [py-pdf/pypdf#2287]
I've got a well worn piece of code that extracts per page dimensions for PDFs. The code in question is:

```python
reader = PdfReader(pdf_path)
mediaboxes = [page.mediabox for page in reader.pages]
```

When I run the attached PDF through this code, I get the message

```
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140029283788224)) invalid; use 0.0 instead
```

printed 47 times, once per page, and the width attribute of each mediabox is 0.0.

The PDF in question loads in PDF viewers. The PDF was last written by Apache PDFBox 3.0.0, so I'd expect it to be compliant to the specification.

## Environment

Which environment were you using when you encountered the problem?

I'm running in a Docker container using the base image `ubuntu:22.04`, which I run `apt-get update --fix-missing`, `apt-get upgrade -y` and `apt-get dist-upgrade -y` on before installing python using `apt-get install -y python3 python3-pip`.

```bash
$ python3 -m platform
Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

$ python3 --version
Python 3.10.12

$ python3 -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.17.0, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=10.0.1
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader

reader = PdfReader('./Zymeworks_Corporate.Presentation_FINAL1101.pdf.pdf')
mediaboxes = [page.mediabox for page in reader.pages]
dimensions = [(mediabox.width, mediabox.height) for mediabox in mediaboxes]
zero_dimensions = [d for d in dimensions if d[0] == 0.0 or d[1] == 0.0]
if zero_dimensions:
    raise Exception(f"Some dimensions have a width or height of zero")
```

[Zymeworks_Corporate Presentation_FINAL1101.pdf.pdf](https://github.com/py-pdf/pypdf/files/13302338/Zymeworks_Corporate.Presentation_FINAL1101.pdf.pdf)

## Traceback

There is no traceback, because no exception is thrown. However I see the following written to the console:

```
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
float() argument must be a string or a real number, not 'IndirectObject' : FloatObject (IndirectObject(720, 0, 140369550894288)) invalid; use 0.0 instead
```

**Comment by SamStephens** [comment]
https://github.com/py-pdf/pypdf/issues/2286 may be related - it also is an issue with `IndirectObject` when using `PdfReader#pages`.

**Comment by stefan6419846** [comment]
Could you please add the complete traceback instead of single-line only error messages?

**Comment by SamStephens** [comment]
> Could you please add the complete traceback instead of single-line only error messages?

Apologies @stefan6419846 I should have been clearer - there is no traceback, because no exception is thrown. What I've put in that section is written to the console during the call to `reader.pages`. I've updated the issue description to hopefully make this clearer.

**Comment by SamStephens** [comment]
Looks like we're hitting https://github.com/py-pdf/pypdf/blob/112bfabd73c2464eb3c969b6cc94138b44acffc5/pypdf/generic/_base.py#L396

**Comment by SamStephens** [comment]
I think https://github.com/py-pdf/pypdf/blob/3fb63f7e3839ce39ac98978c996f3086ba230a20/pypdf/generic/_base.py#L351 should be catching `ValueError` rather than `Exception`. All the except blocks for the other classes in this file catch `ValueError`. The overly broad exception block is masking the exception that should be thrown (hence I don't have a stack trace to share).

If I make the except block change I'm suggesting, the stack trace I see for my example above is

```
>>> reader.pages[0].mediabox
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sam/dev/pypdf/pypdf/_page.py", line 125, in <lambda>
    lambda self: _get_rectangle(self, name, fallback),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/dev/pypdf/pypdf/_page.py", line 109, in _get_rectangle
    retval = RectangleObject(retval)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/dev/pypdf/pypdf/generic/_rectangle.py", line 26, in __init__
    ArrayObject.__init__(self, [self._ensure_is_number(x) for x in arr])  # type: ignore
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/dev/pypdf/pypdf/generic/_rectangle.py", line 26, in <listcomp>
    ArrayObject.__init__(self, [self._ensure_is_number(x) for x in arr])  # type: ignore
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/dev/pypdf/pypdf/generic/_rectangle.py", line 30, in _ensure_is_number
    value = FloatObject(value)
            ^^^^^^^^^^^^^^^^^^
  File "/home/sam/dev/pypdf/pypdf/generic/_base.py", line 349, in __new__
    value = float(str_(value))
            ^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'IndirectObject'
```

The root cause is, as expected, one of the dimensions in the media_box being an `IndirectObject`.

```
>>> reader.pages[0]['/MediaBox']
[0, 0, IndirectObject(720, 0, 140037479660176), 612]
>>> reader.pages[0]['/MediaBox'][2]
IndirectObject(720, 0, 140037479660176)
>>> reader.pages[0]['/MediaBox'][2].get_object()
792
```

What is not clear to me is where the unwrapping of the `IndirectObject` should actually be happening.

Is the appropriate place in `RectangleObject#_ensure_is_number` https://github.com/py-pdf/pypdf/blob/3fb63f7e3839ce39ac98978c996f3086ba230a20/pypdf/generic/_rectangle.py#L28-L31?

**Comment by stefan6419846** [comment]
Thanks for the further analysis.

> Is the appropriate place in `RectangleObject#_ensure_is_number`?

At least it sounds somehow sensible there. Feel free to open a corresponding PR and propose a fix for this - ideally including a corresponding test.

**Comment by SamStephens** [comment]
@stefan6419846 I'm willing to create a PR. Would it be possible to point out some prior art unit tests similar to the test(s) I should write for the changes to `RectangleObject#_ensure_is_number`, as I'm unfamiliar with the testing expectations for the project?

The testing for the change to `FloatObject` seems pretty clear, I should add tests below https://github.com/py-pdf/pypdf/blob/3fb63f7e3839ce39ac98978c996f3086ba230a20/tests/test_generic.py#L50-L59 showing that passing an `IndirectObject` to the constructors of `FloatObject` and `NumberObject` raises an exception.

**Comment by stefan6419846** [comment]
The easiest way is to test `RectangleObject._ensure_is_number` in isolation. Just generate the most common cases as input (`float`, `int`, `FloatObject`, `NumberObject`, `IndirectObject`) and check that the desired value is returned. For the `IndirectObject` case, you might need some mocking/patching to emulate the `get_object` call and the different cases - `IndirectObject.get_object` itself might return another container as well, which probably should be covered here as well.

**Comment by SamStephens** [comment]
@stefan6419846  As far as the possibility that `IndirectObject.get_object` could return a `IndirectObject`, if that's a possibility I think we should have a static method of `IndirectObject` to do this anywhere it's needed, called something like `IndirectObject.fully_unwrap`.

It looks like we probably will want to test the constructor of `RectangleObject` rather than `RectangleObject._ensure_is_number` directly, following existing prior art, and not testing private methods.

I'm not really comfortable introducing new patterns for testing using `IndirectObject`, I'm not seeing any tests that do quite what I need to do, and I'm too new to this to want to introduce new patterns without guidance.

Also, I'm not comfortable using mocking/patching to emulate the `get_object` call; in my experience this is exactly the kind of mocking/patching that ends up generating bugs because of subtle differences between the mocked behavior and the real behavior of the actual class with it's collaborator classes. I'd much rather have some test methods that can create proper `IndirectObject` objects in context of a PdfObject.

One option I see for testing is I see a variety of tests that download PDFs; we could create a test using my sample PDF here.

**Comment by SamStephens** [comment]
I've created https://github.com/py-pdf/pypdf/pull/2460 so we at least have a starting point for this change to discuss.
