### ISSUE TITLE
ROB: page._get_fonts()  gives KeyError: '/BaseFont'

### ISSUE THREAD

**Issue by MartinThoma** [py-pdf/pypdf#2289]
I wanted to get the fonts of a page and got a `KeyError: '/BaseFont'`

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.4.0-166-generic-x86_64-with-glibc2.31

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.17.0, crypt_provider=('cryptography', '41.0.4'), PIL=10.0.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader

reader = PdfReader('missing-base-font.pdf')
page = reader.pages[0]
page._get_fonts()
```

The PDF: 
[missing-base-font.pdf](https://github.com/py-pdf/pypdf/files/13307713/missing-base-font.pdf)

## Traceback

This is the complete Traceback I see:

```
Traceback (most recent call last):
  File "/home/moose/Documents/foo.py", line 5, in <module>
    page._get_fonts()
  File "/home/moose/Github/py-pdf/pypdf/pypdf/_page.py", line 2349, in _get_fonts
    fonts, embedded = _get_fonts_walk(obj, fonts, embedded)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/moose/Github/py-pdf/pypdf/pypdf/_page.py", line 2645, in _get_fonts_walk
    process_font(f)
  File "/home/moose/Github/py-pdf/pypdf/pypdf/_page.py", line 2635, in process_font
    emb.add(cast(str, f["/BaseFont"]))
                      ~^^^^^^^^^^^^^
  File "/home/moose/Github/py-pdf/pypdf/pypdf/generic/_data_structures.py", line 333, in __getitem__
    return dict.__getitem__(self, key).get_object()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '/BaseFont'
```

**Comment by MartinThoma** [comment]
@pubpub-zz I would replace 

```python
            # the list comprehension ensures there is FontFile
            emb.add(cast(str, f["/BaseFont"]))
```

in `_page.py` by

```python
            if (...) and "/BaseFont" in f:
                emb.add(cast(str, f["/BaseFont"]))
```

That would at least make the exception go away. But I don't know why we have that big if-block. I guess there is something else wrong?

**Comment by pubpub-zz** [comment]
The problem here is that the font is a Type 3 that does not contains /BaseFont property.
I would propose this mod:
```
emb.add(cast(str, f.get("/BaseFont","("+f["/SubType"]+")")))
```
about the big if block, so far from I remember I've written it as a list of if but ruff/black optimized it
