### ISSUE TITLE
ValueError: key must be PdfObject 

### ISSUE THREAD

**Issue by shafeeralip** [py-pdf/pypdf#2316]
Hey, I'm pretty sure it's just because I'm doing something wrong

```
Traceback (most recent call last):
  File "/Users/shafeerali/Documents/Nanonets/avanto/API/ap2.py", line 196, in get_page_from_pdf
    image['/Resources']['/ProcSet'] = ['/PDF', '/Text', '/ImageB', '/ImageC', '/ImageI']
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PyPDF2/generic/_data_structures.py", line 253, in __setitem__
    raise ValueError("key must be PdfObject")
ValueError: key must be PdfObject
```

```
input_pdf = PdfReader(dwnld_filepath)
output_pdf = PdfWriter()
image = input_pdf.pages[page_number]
image['/Resources']['/ProcSet'] = ['/PDF', '/Text', '/ImageB', '/ImageC', '/ImageI']
output_pdf.add_page(image)


```

**Comment by stefan6419846** [comment]
PyPDF2 is deprecated and unsupported, please switch to *pypdf*.

Additionally, could you please elaborate on what you are trying to achieve? The issue itself seems to stem from the fact the keys probably should be `NameObject` instances.
