### ISSUE TITLE
Getting KeyError '/Top' when trying to write the file

### ISSUE THREAD

**Issue by zeloras** [py-pdf/pypdf#2351]
Good day! I'm trying to merge few pdf in one and i'm getting /Top KeyError only for one pdf file that i attached. Could you take a look?

## Environment

```bash
$ python -m platform
Linux-6.4.16-linuxkit-aarch64-with-glibc2.36

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.17.1, crypt_provider=('cryptography', '41.0.7'), PIL=9.2.0
```

## Code + PDF

```python
from io import BytesIO
from pypdf import PdfReader, PdfWriter, PdfMerger


def write_to_buffer(writer):
    buffer = BytesIO()
    writer.write(buffer)
    buffer.seek(0)
    return buffer.read()


pdf_merger = PdfMerger()

pdf_reader = PdfReader("D67AF95D-957F-458E-8389-AAC13DA6A51F.pdf")

pdf_writer = PdfWriter()
pdf_writer.append(pdf_reader)

pdf_reader = PdfReader(BytesIO(write_to_buffer(pdf_writer)))
pdf_merger.append(pdf_reader)

output_pdf = write_to_buffer(pdf_merger)

```

[D67AF95D-957F-458E-8389-AAC13DA6A51F.pdf](https://github.com/py-pdf/pypdf/files/13714291/D67AF95D-957F-458E-8389-AAC13DA6A51F.pdf)

## Traceback

```
Traceback (most recent call last):
2023-12-19T09:53:22.719156753Z   File "/opt/project/backend/apps/forms/views/print.py", line 315, in write_to_buffer
2023-12-19T09:53:22.719158294Z     writer.write(buffer)
2023-12-19T09:53:22.719159919Z   File "/usr/local/lib/python3.10/site-packages/pypdf/_merger.py", line 333, in write
2023-12-19T09:53:22.719161419Z     self._write_outline()
2023-12-19T09:53:22.719168253Z   File "/usr/local/lib/python3.10/site-packages/pypdf/_utils.py", line 469, in wrapper
2023-12-19T09:53:22.719170669Z     return func(*args, **kwargs)
2023-12-19T09:53:22.719172169Z   File "/usr/local/lib/python3.10/site-packages/pypdf/_merger.py", line 548, in _write_outline
2023-12-19T09:53:22.719173711Z     self._write_outline_item_on_page(outline_item, page)
2023-12-19T09:53:22.719175211Z   File "/usr/local/lib/python3.10/site-packages/pypdf/_utils.py", line 469, in wrapper
2023-12-19T09:53:22.719176753Z     return func(*args, **kwargs)
2023-12-19T09:53:22.719178253Z   File "/usr/local/lib/python3.10/site-packages/pypdf/_merger.py", line 580, in _write_outline_item_on_page
2023-12-19T09:53:22.719180003Z     del outline_item[arg_key]
2023-12-19T09:53:22.719185586Z KeyError: '/Top'
```

**Comment by stefan6419846** [comment]
*PdfMerger* is deprecated, please move to *PdfWriter*.

**Comment by zeloras** [comment]
Thank you! It works 🙏
