### ISSUE TITLE
AttributeError: 'Page' object has no attribute 'super'

### ISSUE THREAD

**Issue by NtSalazar** [py-pdf/pypdf#2420]
Hi!, i have an error when i try to modify an url in a pdf. the error disappear when you remove the ".super()"

## Environment
Microsoft Windows 11 Pro 10.0.22000 N/A Build 22000
python = "Python 3.12.1"
pymupdf = "1.23.16"

## Code + PDF
```cmd
poetry run python test.py
```

test.py
```python
import fitz
# update the link
with fitz.open("modify-url.pdf") as pdf:
  links = pdf[0].get_links()
  links[0]['uri'] = "https://www.ddg.gg"
  pdf[0].update_link(links[0])
  pdf.save("output.pdf")
```
[modify-url.pdf](https://github.com/py-pdf/pypdf/files/14002738/modify-url.pdf)
you can use the files in whatever you want

## Traceback

This is the complete traceback I see:
```
Traceback (most recent call last):
  File "test.py", line 328, in <module>
    Send_Accessing_Message(user, response_message)
  File "test.py", line 240, in Send_Accessing_Message
    pdf[0].update_link(links[0])
  File "C:\Users\computer_name\AppData\Local\pypoetry\Cache\virtualenvs\main-S6_UyEDV-py3.8\lib\site-packages\fitz\utils.py", line 1716, in update_link
    page.parent.update_object(lnk["xref"], annot, page=page)
  File "C:\Users\computer_name\AppData\Local\pypoetry\Cache\virtualenvs\main-S6_UyEDV-py3.8\lib\site-packages\fitz\__init__.py", line 5615, in update_object
    JM_refresh_links( mupdf.pdf_page_from_fz_page(page.super()))
AttributeError: 'Page' object has no attribute 'super'
```

**Comment by NtSalazar** [comment]
IM SO SORRY, i posted this thing in the wrong repo; WTF
