### ISSUE TITLE
KeyError: '/A'

### ISSUE THREAD

**Issue by pingorczinger** [py-pdf/pypdf#2517]
I was trying to extract urls from PDF file with this simple code but encountered an error "KeyError: '/A'"
## Environment

OS: Windows 10
Python 3.12.2
pypdf 4.1.0

## Code + PDF
```python
with open(PdfFile, "rb") as LinkSource:
    PDF = PdfReader(LinkSource)
    pages = len(PDF.pages)
    key = '/Annots'
    uri = '/URI'
    ank = '/A'

    for page in range(pages):
        pageSliced = PDF.pages[page]
        pageObject = pageSliced.get_object()
        if key in pageObject.keys():
            ann = pageObject[key]
            for a in ann:
                u = a.get_object()
                if uri in u[ank].keys():
                    print(u[ank][uri])
```

Example u value:
```
{'/Subtype': '/Link', '/Rect': [186.63, 478.9, 422.02, 504.34], '/BS': {'/W': 0}, '/F': 4, '/A': {'/Type': '/Action', '/S': '/URI', '/URI': 'https://[censored]'}, '/StructParent': 277}
```
## Traceback

This is the complete traceback I see:

```
Traceback (most recent call last):
  File "c:\[censored]\grabber.py", line 24, in <module>
    if uri in u[ank].keys():
              ~^^^^^
  File "C:\[censored]\AppData\Roaming\Python\Python312\site-packages\pypdf\generic\_data_structures.py", line 319, in __getitem__
    return dict.__getitem__(self, key).get_object()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '/A'
```

**Comment by pubpub-zz** [comment]
This is a proposal to review/validate/test:
```
from pypdf import PdfReader

pdf = PdfReader(PdfFile)
    for page in pdf.pages:
        for ano in page.get("/Annots",()):
           for a in ano:
                a = a.get_object()
                if "/A" in a:
                     if "/URI" in a["/A"]:
                         print(a["/A"]["/URI"])
```

**Comment by pingorczinger** [comment]
@pubpub-zz 
Now I get error "Key Error: 0"
```
Traceback (most recent call last):
  File "c:\[censored]\grabber.py", line 20, in <module>
    for a in ano:
  File "C:\[censored]\AppData\Roaming\Python\Python312\site-packages\pypdf\generic\_base.py", line 309, in __getitem__
    return self._get_object_with_check()[key]  # type: ignore
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\[censored]\AppData\Roaming\Python\Python312\site-packages\pypdf\generic\_data_structures.py", line 319, in __getitem__
    return dict.__getitem__(self, key).get_object()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 0
```

Could the fact that the object has two "/URI" keys cause this problem?

**Comment by pubpub-zz** [comment]
can you please share the pdf for test

**Comment by pingorczinger** [comment]
> can you please share the pdf for test

Unfortunately no, this is rather confidential file. I can provide as much diagnostic info as I can if needed but without entire PDF.

**Comment by pubpub-zz** [comment]
oups!!! 
found my mistake:
```
from pypdf import PdfReader

pdf = PdfReader(PdfFile)
for page in pdf.pages:
           ano=page.get("/Annots",())
           for a in ano:
                a = a.get_object()
                if "/A" in a:
                     if "/URI" in a["/A"]:
                         print(a["/A"]["/URI"])
```

**Comment by pingorczinger** [comment]
@pubpub-zz it worked now :) thanks
