### ISSUE TITLE
Documentation: Adding internal link code snippet is incorrect.

### ISSUE THREAD

**Issue by jparris** [py-pdf/pypdf#2751]
The code snippet for adding [an Internal Link](https://pypdf.readthedocs.io/en/stable/user/adding-pdf-annotations.html?highlight=link) is out of date. `Link` does not accept fit_args, Instead a `Fit` object needs to be constructed.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-13.5.2-arm64-arm-64bit

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==4.2.0, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=none
```

## Code + PDF

Sliently modified from the docs code snippet

```python
from pypdf import PdfReader, PdfWriter
from pypdf.annotations import Link

reader = PdfReader("./foo.pdf")
page = reader.pages[0]
writer = PdfWriter()
writer.add_page(page)

# Add the line
annotation = Link(
    rect=(50, 550, 200, 650), target_page_index=3, fit="/FitH", fit_args=(123,)  # This line contains the error.
)
writer.add_annotation(page_number=0, annotation=annotation)

# Write the annotated file to disk
with open("annotated-pdf.pdf", "wb") as fp:
    writer.write(fp)

…/pypdf_rewrite_urls on  main ls
EXAScaler-6.3.1-features-and-procedures-guide.pdf  README.md  bar.pdf  flake.lock  flake.nix  foo.pdf  poetry.lock  pyproject.toml  sample_package  test.py

…/pypdf_rewrite_urls on  main vim test.py 

…/pypdf_rewrite_urls on  main cat test.py 
from pypdf import PdfReader, PdfWriter
from pypdf.annotations import Link

reader = PdfReader("./foo.pdf")
page = reader.pages[0]
writer = PdfWriter()
writer.add_page(page)

# Add the line
annotation = Link(
    rect=(50, 550, 200, 650), target_page_index=3, fit="/FitH", fit_args=(123,)
)
writer.add_annotation(page_number=0, annotation=annotation)

# Write the annotated file to disk
with open("annotated-pdf.pdf", "wb") as fp:
    writer.write(fp)
```

Share here the PDF file(s) that cause the issue. The smaller they are, the
better. Let us know if we may add them to our tests!
N/A a PDF is not constructed.

## Traceback

This is the complete traceback I see:

```
python test.py 
Traceback (most recent call last):
  File "/Users/jparris/src/pypdf_rewrite_urls/test.py", line 10, in <module>
    annotation = Link(
                 ^^^^^
  File "/nix/store/0png4ni3v5y44vi1pc7nvj32niivqajd-python3-3.12.4-env/lib/python3.12/site-packages/pypdf/annotations/_markup_annotations.py", line 310, in __init__
    super().__init__(**kwargs)
TypeError: MarkupAnnotation.__init__() got an unexpected keyword argument 'fit_args'
```

## The solution
```python
from pypdf import PdfReader, PdfWriter
from pypdf.annotations import Link
from pypdf.generic import Fit

reader = PdfReader("./foo.pdf")
page = reader.pages[0]
writer = PdfWriter()
writer.add_page(page)

# Add the line
annotation = Link(
    rect=(50, 550, 200, 650), target_page_index=3, fit=Fit(fit_type="/FitH", fit_args=(123,)).   # This the change that is needed
)
writer.add_annotation(page_number=0, annotation=annotation)

# Write the annotated file to disk
with open("annotated-pdf.pdf", "wb") as fp:
    writer.write(fp)
```

**Comment by stefan6419846** [comment]
Thanks for the report. Do you want to submit a corresponding PR to fix this?

**Comment by jparris** [comment]
Sure. I've opened https://github.com/py-pdf/pypdf/pull/2759 .
