### ISSUE TITLE
5.0.0 should not be pip installable for Python < 3.8

### ISSUE THREAD

**Issue by zmeves** [py-pdf/pypdf#2858]
`pypdf 5.0.0` is pip-installable for Python 3.7, but support for 3.7 is dropped as noted in the [Changelog](https://pypdf.readthedocs.io/en/stable/meta/CHANGELOG.html#version-5-0-0-2024-09-15).

Packages that require `pypdf > X` but don't specify `<5` are subject to erroneously installing `pypdf >= 5` when running on Python 3.7.

## Environment

Python 3.7, any OS

```bash
$ python -m platform
Windows-10-10.0.22621-SP0

$ python -c "import pypdf;print(pypdf._debug_versions)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\zmeve\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\__init__.py", line 11, in <
module>
    from ._doc_common import DocumentInformation
  File "C:\Users\zmeve\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\_doc_common.py", line 48, i
n <module>
    from ._encryption import Encryption
  File "C:\Users\zmeve\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\_encryption.py", line 46, i
n <module>
    from ._utils import logger_warning
  File "C:\Users\zmeve\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\_utils.py", line 523, in <m
odule>
    @dataclass
  File "C:\Users\zmeve\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\_utils.py", line 525, in Fi
le
    from .generic import IndirectObject
  File "C:\Users\zmeve\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\generic\__init__.py", line
38, in <module>
    from ._base import (
  File "C:\Users\zmeve\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\generic\_base.py", line 37,
 in <module>
    from .._protocols import PdfObjectProtocol, PdfWriterProtocol
  File "C:\Users\zmeve\AppData\Local\Programs\Python\Python37\lib\site-packages\pypdf\_protocols.py", line 5, in
<module>
    from typing import IO, Any, Dict, List, Optional, Protocol, Tuple, Union
ImportError: cannot import name 'Protocol' from 'typing' (C:\Users\zmeve\AppData\Local\Programs\Python\Python37\l
ib\typing.py)
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
import pypdf
print(pypdf.__version__)
```

## Traceback

Same as listed above.

## Suggested Fixes

1. Update the `pyproject.toml` to mark the minimum Python version as 3.8
2. "Yank" the `pypdf 5.0.0` distribution from PyPI for Python 3.7. I'm not sure if this is possible for a specific Python version - if not, it may still be best to yank the entire 5.0.0 release and re-publish it as 5.0.0.post1, or even 5.0.1.

**Comment by weeix** [comment]
I pinned `xhtml2pdf==0.2.11`, but it requires `pypdf>=3.1.0`, so I added `pypdf==4.3.1` to my requirements.txt to fix the error.

**Comment by pubpub-zz** [comment]
I have no strong opinion. I'm OK ready to publish 5.0.1 this week-end if the change in pyproject.toml is OK.
As @stefan6419846  said, @MartinThoma may have to yank 5.0.0
