### ISSUE TITLE
Can't read pdf

### ISSUE THREAD

**Issue by aruscher** [py-pdf/pypdf#57]
I get an mysterious error with the PDF Reader using python3 on the file 
"Werner - Fragen und Antworten zu Werkstoffen.pdf". 
My Code:

``` python
import fnmatch
import os
from PyPDF2 import PdfFileReader

for file in os.listdir('.'):
    if fnmatch.fnmatch(file,'*.pdf'):
        print("File: "+file)
        foo = PdfFileReader(open(file,"rb"))
```

Error:

```
File: Werner - Fragen und Antworten zu Werkstoffen.pdf
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    foo = PdfFileReader(open(file,"rb"))
  File "/usr/lib/python3.3/site-packages/PyPDF2/pdf.py", line 684, in __init__
    self.read(stream)
  File "/usr/lib/python3.3/site-packages/PyPDF2/pdf.py", line 1236, in read
    streamData = BytesIO(xrefstream.getData())
  File "/usr/lib/python3.3/site-packages/PyPDF2/generic.py", line 834, in getData
    decoded._data = filters.decodeStreamData(self)
  File "/usr/lib/python3.3/site-packages/PyPDF2/filters.py", line 310, in decodeStreamData
    data = FlateDecode.decode(data, stream.get("/DecodeParms"))
  File "/usr/lib/python3.3/site-packages/PyPDF2/filters.py", line 121, in decode
    rowdata = [ord(x) for x in data[(row*rowlength):((row+1)*rowlength)]]
  File "/usr/lib/python3.3/site-packages/PyPDF2/filters.py", line 121, in <listcomp>
    rowdata = [ord(x) for x in data[(row*rowlength):((row+1)*rowlength)]]
TypeError: ord() expected string of length 1, but int found
```

Is smth broken with my filename or why this error occurs?

**Comment by jguram** [comment]
I am facing the same issue @mstamy2  can you please help me
