### ISSUE TITLE
PDFFileMerger : PdfReadWarning: Xref table not zero-indexed. ID numbers for objects will  be corrected. [pdf.py:1736]

### ISSUE THREAD

**Issue by CheriseCodes** [py-pdf/pypdf#611]
**The code**

```
inputs = ["C:/Users/user/Desktop/file1.pdf", "C:/Users/user/Desktop/file2.pdf", "C:/Users/user/Desktop/file3.pdf"]

writer = PdfFileMerger()

for inpfn in inputs:
    f = open(inpfn, 'rb')
    writer.append(PdfFileReader(f))
    f.close()

writer.write("merged.pdf")
```

**Expected Behaviour**

Files are merged into a file called merged.pdf 

**Actual Behaviour**

I recieve this error message and files are not merged.

```
PdfReadWarning: Xref table not zero-indexed. ID numbers for objects will 
be corrected. [pdf.py:1736]
Traceback (most recent call last):
  File "C:\Users\user\Desktop\mergepdfs.py", line 12, in <module>
    writer.append(PdfFileReader(f))
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PyPDF2\pdf.py", line 1084, in __init__
    self.read(stream)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\PyPDF2\pdf.py", line 1883, in read
    stream.seek(-11, 1)
OSError: [Errno 22] Invalid argument
```

**Comment by pubpub-zz** [comment]
@CheriseCodes can you provide some pdf sample and a test code for analysis

**Comment by pubpub-zz** [comment]
@CheriseCodes,
I've used the 3 tests files from https://github.com/mvicenzi/pdf_tools/tree/2-find-a-work-around-for-scanned-pdf/test without issues.

 I've tried with the development version and without any trouble. can you confirm you still have the problem?

**Comment by pubpub-zz** [comment]
@MartinThoma, I wish we could get below 100 open issues 😎
