### ISSUE TITLE
PyPDF2.utils.PdfReadError: Creating EncodedStreamObject is not currently supported

### ISSUE THREAD

**Issue by hari0805** [py-pdf/pypdf#656]
My task is  to find and replace the text in pdf, I used pyPDF2 package to replace the text, but when I try to replace I'm receiving an error like 

```
Traceback (most recent call last):
  File "c:\practice_python\sample.py", line 41, in <module>
    page.getContents().setData(replaced_text)
  File "C:\Users\Win\AppData\Local\Programs\Python\Python310\lib\site-packages\PyPDF2\generic.py", line 852, in setData
    raise utils.PdfReadError("Creating EncodedStreamObject is not currently supported")
PyPDF2.utils.PdfReadError: Creating EncodedStreamObject is not currently supported
```

and my code is 

```python
from PyPDF2 import PdfFileReader, PdfFileWriter

replacements = [
    ("HARIHARAN S", "<your name>")
]

pdf = PdfFileReader(open("samplenda.pdf", "rb"))
writer = PdfFileWriter() 

for page in pdf.pages:
    contents = page.getContents().getData()
    print(type(contents))
    for (a,b) in replacements:
        replaced_text = contents.replace(bytes(a,'utf-8'), bytes(b,'utf-8'))  # .encode('utf-8')
    print(type(replaced_text))
    page.getContents().setData(replaced_text)
    writer.addPage(page)
    
with open("modified.pdf", "wb") as f:
     writer.write(f)
```

I tried lots of way many times, please help me to solve this error

**Comment by SpastBanana** [comment]
Hi,

Is there any update on this? I got the same error as @ghost

**Comment by stefan6419846** [comment]
Please open a new issue, filling all the necessary details.
